### ISSUE TITLE
Issue with valid number check

### ISSUE THREAD

**Issue by shrey-gang** [daviddrysdale/python-phonenumbers#104]
I used this library in one of my projects but I am facing an issue with number validity, the "**is_possible_number**" gives output as True even if I give a valid number but incorrect country/region code.
For eg: I tried with an indian number with country code '+504', and the output was valid.

I would appreciate if you can help me with this issue, is it that I am calling a wrong function or issue in library.

**Comment by daviddrysdale** [comment]
I'd need more details (preferably a short code sample) to help more, but a number starting with **+** will typically be parsed as an [E.164](https://en.wikipedia.org/wiki/E.164) number regardless of the region.

**Comment by shrey-gang** [comment]
Below code gives output as true for starting 91 as well as 504 in place of 91
```
phone_number = '9198290xxxxx'   # valid indian airtel carier number
x = phonenumbers.parse(phone_number, None)
valid_number = phonenumbers.is_possible_number(x)
```

output is TRUE

**Comment by daviddrysdale** [comment]
That gives a `NumberParseException` on the `parse` because you're not specifying a default region -- phonenumbers are only globally unique in E.164 format, so a number without a leading + can only be parsed relative to a region.

**Comment by shrey-gang** [comment]
I tried what you suggested once again:
input: +81098290xxxxx
output: True
 **+810** is the international country code for "**Kazakhstan**" and phone number is Indian which with Indian code +91 gives correct output.

The actual output should be False.
I took country codes from this link => [Country Codes](http://www.nationsonline.org/oneworld/international-calling-codes.htm)

**Comment by daviddrysdale** [comment]
810 is not the international country code for Kazakhstan, it's the international dial prefix for Kazakhstan (i.e. what you would start dialling with to get to an international number when in Kazakhstan).

Kazakhstan is reached via international country code +7 (bundled in with the Russian Federation).

+810 would actually fall under +81, which is the country code for Japan.  

```pycon
>>> import phonenumbers
>>> input = '+8109829012345'
>>> x = phonenumbers.parse(input, None)
>>> phonenumbers.is_possible_number(x)
True
>>> print x
Country Code: 81 National Number: 9829012345
>>> from phonenumbers import geocoder
>>> geocoder.country_name_for_number(x, "en")
u'Japan'
```
