### ISSUE TITLE
wheel of phonenumberslite still contains geo data

### ISSUE THREAD

**Issue by moggers87** [daviddrysdale/python-phonenumbers#105]
This can easily be observed by looking at the file sizes of the wheel versus source distribution on pypi: https://pypi.python.org/pypi/phonenumberslite/8.8.1

Downloading each and inspecting them confirms that the wheel contains `geodata` and the source tarball does not (as should be the case).

**Comment by daviddrysdale** [comment]
Good spot, I'd not noticed that. I think I'm falling foul of [wheel issue #147](https://github.com/pypa/wheel/issues/147): when I build the lite version it picks up the build detritus from the build of the full version and includes it.

**Comment by daviddrysdale** [comment]
I'll mark this as closed; the next release should have the smaller wheel (IIRC PyPI doesn't allow changes to existing packages).
