### ISSUE TITLE
Zambia number not recognized as valid

### ISSUE THREAD

**Issue by bineyame** [daviddrysdale/python-phonenumbers#109]
Valid Zambia number is not recognized as such
`In [2]: n='+260956439422'

In [3]: m=phonenumbers.parse(n,'ZM')

In [4]: phonenumbers.is_possible_number(m)
Out[4]: True

In [5]: phonenumbers.is_valid_number(m)
Out[5]: False

In [6]:  phonenumbers.__version__
Out[6]: '8.8.5'
`

**Comment by daviddrysdale** [comment]
The upstream Java code gives the [same result](http://libphonenumber.appspot.com/phonenumberparser?number=%2B260956439422&country=ZM), so please raise an [issue there](https://github.com/googlei18n/libphonenumber/issues/new).
