### ISSUE TITLE
Phone numbers start with 07

### ISSUE THREAD

**Issue by youssefhajari** [daviddrysdale/python-phonenumbers#111]
Hello,
First of all, thank you for your effort,
In France phone numbers can now start with '07', but when i want to create a new phone number i have an error [ [+33 7 ** ** ** **] Phone Number not correct!]] , i think the bug is from the file 'phonenumbers/data/region_FR.py' the mobile pattern just take  '06' .
How can i patch this module to fix this bug ?

**Comment by daviddrysdale** [comment]
Some French numbers starting with 7 seem to work OK for me, but looking at the [metadata](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L7943), it seems 70..., 71..., 72... numbers aren't expected to be valid mobile numbers.

If you think the metadata isn't accurate/up-to-date, the best thing is to [report the problem](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue) to the upstream [libphonenumber project](https://github.com/googlei18n/libphonenumber).

```pycon
>>> import phonenumbers
>>> x = phonenumbers.parse("0731234567", "FR")
>>> phonenumbers.is_valid_number(x)
True
>>> x
PhoneNumber(country_code=33, national_number=731234567, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> y = phonenumbers.parse("+33 731234567", "")
>>> phonenumbers.is_valid_number(y)
True
>>> y
PhoneNumber(country_code=33, national_number=731234567, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> y = phonenumbers.parse("+33 711234567", "")
>>> phonenumbers.is_possible_number(y)
True
>>> phonenumbers.is_valid_number(y)
False
```

**Comment by browniebroke** [comment]
For whoever hit this as well (like me), linking to my submission to the upstream Google issue tracker: https://issuetracker.google.com/issues/285169031
