### ISSUE TITLE
issue with italian numbers

### ISSUE THREAD

**Issue by smorel2b** [daviddrysdale/python-phonenumbers#112]
Hi, i have trouble with italian number, 
```
    >>> n2='0656851242'
    >>> n3='335022670'
    >>> obj2=phonenumbers.parse(n2,'IT')

    PhoneNumber(country_code=39, national_number=656851242, extension=None, italian_leading_zero=True, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)

    >>> obj3=phonenumbers.parse(n3,'IT')

    PhoneNumber(country_code=39, national_number=335022670, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)

    >>> phonenumbers.is_valid_number(obj2)
   True
    >>> phonenumbers.is_valid_number(obj3)
   True

    >>> phonenumbers.format_number(obj2, phonenumbers.PhoneNumberFormat.E164)
    u'+390656851242'
    >>> phonenumbers.format_number(obj3, phonenumbers.PhoneNumberFormat.E164)
    u'+39335022670'
```

But the number n3 & obj3 should be refused normaly cause he just have 9 digit, not 10
any idea?

**Comment by daviddrysdale** [comment]
The [upstream Java code](https://github.com/googlei18n/libphonenumber) also says that both [n2](http://libphonenumber.appspot.com/phonenumberparser?number=0656851242&country=IT) and [n3](http://libphonenumber.appspot.com/phonenumberparser?number=335022670&country=IT) are valid, so this isn't something specific to the Python port.

It might be to do with '[Italian leading zeros](https://github.com/googlei18n/libphonenumber/blob/master/resources/phonenumber.proto#L57-L73)' but you're best off asking the experts upstream I'm afraid.
