### ISSUE TITLE
By when can we expect new release . (Facing issue in formatting of +916360248400).

### ISSUE THREAD

**Issue by taju20910** [daviddrysdale/python-phonenumbers#113]
Sorry for raising this as an issue . Found no other way out here .

**Comment by daviddrysdale** [comment]
That's really a question for [upstream](https://github.com/googlei18n/libphonenumber) -- I usually track their releases within a few days.

However, a [message on the mailing list](https://groups.google.com/d/msg/libphonenumber-discuss/8dqzzlE2FMo/a4cnfWCdCwAJ) indicated a possible release in 2nd or 3rd week of January.

**Comment by taju20910** [comment]
Thanks David.

**Comment by taju20910** [comment]
Hey David,

Hope you will be doing well. I just checked the [mailing list](https://groups.google.com/forum/#!msg/libphonenumber-discuss/8dqzzlE2FMo/a4cnfWCdCwAJ) .  They  have made 8.8.9 release yesterday. 
Can you please confirm by when are you planning to integrate it.
