### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by vvknain** [daviddrysdale/python-phonenumbers#114]
In [41]: x = phonenumbers.parse('+917878787xyz', None)

In [42]: print x
Country Code: 91 National Number: 7878787999

i couldn't find a way to to workaround this problem. Any help?

**Comment by daviddrysdale** [comment]
You don't actually say what your 'error' or 'problem' is, but I'm guessing it's that the 'xyz' at the end is being parsed as a [vanity number](https://en.wikipedia.org/wiki/Vanity_number).

The Python code behaves the [same as the Java code](http://libphonenumber.appspot.com/phonenumberparser?number=%2B917878787xyz), and I believe this is deliberate behaviour on their part  -- see googlei18n/libphonenumber#1199 for more information.
