### ISSUE TITLE
Making a standalone executable?

### ISSUE THREAD

**Issue by gitdjc** [daviddrysdale/python-phonenumbers#115]
I've written a batch program using phonenumbers. On my Windows system with Python 3.6.4 installed, it works as intended, but I'd like to redistribute it as a standalone Windows executable. However, I'm hitting two barriers: first, I'm a rank beginner with Python, and the details of the Python environment are still a slog for me. Second, the .EXE program throws an exception in trying to dynamically load country data to parse a number, and I haven't managed to figure out how to incorporate dynamically loaded modules into a standalone executable. (The failure was in a "try" clause, so it took me a while to locate it.) My own system has all the memory I'd need to preload all parsing data up front, so I'd prefer to do things that way.

Solutions, suggestions, hints, thoughts? A fully-worked example somewhere?

**Comment by daviddrysdale** [comment]
Sorry, I've got no idea about building standalone Windows `.exe`s I'm afraid.
