### ISSUE TITLE
How to test this when we need lot of unique numbers ?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [daviddrysdale/python-phonenumbers#116]
Hello, guys, awesome package but [python-faker](https://github.com/joke2k/faker) fails to generate suitable phone number

How we can generate lot of unique numbers ? I think it's related to this package.

**Comment by daviddrysdale** [comment]
`example_number(region_code)` will give an valid example number for a particular region; you could try variations in the trailing digits of that.

**Comment by ArtemBernatskyy** [comment]
Ok, thx @daviddrysdale
