### ISSUE TITLE
Create your own number format

### ISSUE THREAD

**Issue by Koyirov** [daviddrysdale/python-phonenumbers#119]
Hello,
Can someone show me an example how to create your own number format. I need "+49 xxx xxxxxxxxx"  format to use the function format_by_pattern(num_obj, NumberFormat, new_number_format). I haven't found on the Internet an example for python. Thank you in advance.

**Comment by daviddrysdale** [comment]
There are examples of `format_by_pattern` [in the tests](https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/tests/phonenumberutiltest.py#L860-L915).

**Comment by Koyirov** [comment]
Thank you very much!

**Comment by Koyirov** [comment]
There is my code:

number = '+491623276631'
num_obj = ph.parse(number)

new_number_format = ph.NumberFormat(pattern="(\\d{3})(\\d{*})", format="\\1  \\2")
new_number_format._mutable = True
newNumberFormats = [new_number_format]

new_form = ph.format_by_pattern(num_obj, ph.PhoneNumberFormat.INTERNATIONAL, newNumberFormats)
print(new_form).

but I can't get my desired result. The result is '+49 1623276631', I want to have '+49 162 3276631'. What's the problem here?

**Comment by Koyirov** [comment]
the problem has been solved. Thanks!
