### ISSUE TITLE
Parsing numbers starting with 00 and unknown region

### ISSUE THREAD

**Issue by genieakhadrah** [daviddrysdale/python-phonenumbers#121]
I'm trying to parse a number which starts with 00 ex 00962791234567 and the region ZZ its not parsing the number and throwing an exception while parsing +962791234567 with region ZZ works like a charm. 

Isn't 00 suppose to behave same as + ?

**Comment by daviddrysdale** [comment]
No, [00 isn't supposed to behave the same as +](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-wasnt-00-parsed-the-same-as-), it's country-specific.
