### ISSUE TITLE
Make the __repr__ method look similar to SRE_Match's __repr__ method

### ISSUE THREAD

**Issue by calebbredlow** [daviddrysdale/python-phonenumbers#126]
Instead of doing 
```python
    def __repr__(self):
        return (unicod("PhoneNumberMatch(start=%r, raw_string=%r, numobj=%r)") %
                (self.start,
                 self.raw_string,
                 self.number))

    def __unicode__(self):
        return unicod("PhoneNumberMatch [%s,%s) %s") % (self.start, self.end, self.raw_string)
```

do something similar to re.match's __repr__ method and do 
`"<phonenumbers.PhoneNumberMatch; start={}, end={}, raw_string={}>".format(self.start, self.end, self.raw_string)`
maybe even convert the start and end into a tuple and have it be span?

**Comment by cbredlow** [comment]
https://github.com/daviddrysdale/python-phonenumbers/pull/127

**Comment by daviddrysdale** [comment]
As commented on #127, I'm not keen on changing the format just to make things look nicer, in case there's anything relying on the current format.

(Also, as an aside, the `__repr__` method does aim to "return a string that would yield an object with the same value when passed to `eval()`", as per the [docs](https://docs.python.org/3/library/functions.html#repr).)
