### ISSUE TITLE
JPEG File like a phone number using scrapy body with PhoneNumberMatcher

### ISSUE THREAD

**Issue by GilbertoBitt** [daviddrysdale/python-phonenumbers#129]
I used "for phone in phonenumbers.PhoneNumberMatcher(bodyString, "BR"):"
on this specific page: http://www.belem.pa.gov.br/belemtur/site/?paged=2
and then it returned this number: tel:+55-17-5694-1024;ext=542 (PhoneNumberR(phonenumbers.format_number
- phone.number, phonenumbers.PhoneNumberFormat.RFC3966) < Using this format to save numbers found.
but there's no number on this page but when I search for parts of the number I found the "number" that lib found. "http://www.belem.pa.gov.br/belemtur/site/wp-content/uploads/2015/10/60577_175694-300x159.jpg" he detects part of this link name has a phone number. so how should I proceed with any tips?

**Comment by daviddrysdale** [comment]
Have you tried changing the `leniency` parameter to `PhoneNumberMatcher`?  `STRICT_GROUPING` or `EXACT_GROUPING` might reduce the false positives (with a trade-off of not matching phonenumbers that don't have the correct local grouping).
