### ISSUE TITLE
Phone number not matched

### ISSUE THREAD

**Issue by TheDevelolper** [daviddrysdale/python-phonenumbers#130]
Hi Sorry if this is a duplicate issue. I tried to comment on a previous similar issue but it was closed so I was told to raise a new one. 

this number doesn't seem to work with the code below 020 7851 7813

for match in phonenumbers.PhoneNumberMatcher(text, "gb", phonenumbers.Leniency.POSSIBLE):
    n = phonenumbers.format_number(match.number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
    print(n)

**Comment by daviddrysdale** [comment]
`"gb"` is not a [country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2); the code works with `"GB"`:
```pycon
Python 3.7.1 (default, Oct 21 2018, 05:48:29) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> text = "this number doesn't seem to work with the code below 020 7851 7813"
>>> for match in phonenumbers.PhoneNumberMatcher(text, "GB", phonenumbers.Leniency.POSSIBLE):
...   n = phonenumbers.format_number(match.number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
...   print(n)
... 
+44 20 7851 7813
```
