### ISSUE TITLE
Update Acceptable Area Codes

### ISSUE THREAD

**Issue by vchunduru93** [daviddrysdale/python-phonenumbers#133]
Hello there,

There is an area code ('279') that is not supported by your library. I checked with https://github.com/googlei18n/libphonenumber and it supports this new area code. Please update your metadata so that this new area code is supported by this library.

Thank you!

**Comment by daviddrysdale** [comment]
Please re-open with more details:
 - Area code for which country?
 - What version of python-phonenumbers library are you using?
 - What is the failure / error code, and what does the Java code give for the same input?
