### ISSUE TITLE
Regex performance using re2

### ISSUE THREAD

**Issue by vlordier** [daviddrysdale/python-phonenumbers#139]
Since we are heavily relying on regex here, it makes sense to focus on performance.
Google released re2 https://github.com/google/re2
Intel released hypersacan https://www.hyperscan.io/

**Comment by daviddrysdale** [comment]
This is a pure Python implementation; re2 is C++ based and hyperscan is C based.

**Comment by vlordier** [comment]
I thought to use either :
- Facebook python wrapper https://github.com/facebook/pyre2
- wrapper for hyperscan https://github.com/darvid/python-hyperscan
