### ISSUE TITLE
PhoneMetadata.same_mobile_and_fixed_line_pattern is incorrectly derived

### ISSUE THREAD

**Issue by stefanfisk** [daviddrysdale/python-phonenumbers#141]
This line compares the whole number descriptions:

https://github.com/daviddrysdale/python-phonenumbers/blob/168a1f1e80502544089bc0739670a324730c09bb/python/phonenumbers/phonemetadata.py#L452

But upstream only compares the patterns:

https://github.com/googlei18n/libphonenumber/blob/7cfcd7fe533d82a45c441c0b5f01400435f0dc79/tools/java/common/src/com/google/i18n/phonenumbers/BuildMetadataFromXml.java#L510

For `DK` this was broken in v8.9 because although the patterns were equal the example numbers were different:

https://github.com/daviddrysdale/python-phonenumbers/blob/ad34567d0275be3e6c1de2d72f7b015c315f2fe3/python/phonenumbers/data/region_DK.py

The metadata for `DK` no longer triggers this bug, I believe that the code itself is still broken, and that the same issue could arise again?

**Comment by daviddrysdale** [comment]
Good detective work!
