### ISSUE TITLE
Compile with centos6

### ISSUE THREAD

**Issue by nicoonline** [daviddrysdale/python-phonenumbers#143]
Please do not report issues that can be reproduced with the [upstream Java project](https://github.com/googlei18n/libphonenumber): if your issue can be reproduced with the [online Java demo](http://libphonenumber.appspot.com/), report your [problem upstream](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue) instead.

In particular, any changes to the phonenumber metadata or to the API should be reported upstream rather than here.  Only issues or contributions that are **specific to the Python version** are relevant here.

Hello,
Can we compile your software with centos6 (protobuf 2.3)
Thanks

**Comment by daviddrysdale** [comment]
I would imagine so -- it's a pure Python library, and the main part of the library doesn't directly use protobufs.

**Comment by nicoonline** [comment]
Hello David,
Because we have build errors:

[  117s] /usr/include/google/protobuf/repeated_field.h: In function 'i18n::phonenumbers::PhoneNumberUtil::ValidationResult i18n::phonenumbers::<unnamed>::TestNumberLength(const std::string&, const i18n::phonenumbers::PhoneMetadata&, i18n::phonenumbers::PhoneNumberUtil::PhoneNumberType)':
[  117s] /usr/include/google/protobuf/repeated_field.h:130: error: 'google::protobuf::RepeatedField<Element>::RepeatedField(const google::protobuf::RepeatedField<Element>&) [with Element = int]' is private
[  117s] /home/abuild/rpmbuild/BUILD/libphonenumber-8.10.6/cpp/src/phonenumbers/phonenumberutil.cc:334: error: within this context
[  117s] /usr/include/google/protobuf/repeated_field.h:130: error: 'google::protobuf::RepeatedField<Element>::RepeatedField(const google::protobuf::RepeatedField<Element>&) [with Element = int]' is private
[  117s] /home/abuild/rpmbuild/BUILD/libphonenumber-8.10.6/cpp/src/phonenumbers/phonenumberutil.cc:336: error: within this context
[  117s] /usr/include/google/protobuf/repeated_field.h:130: error: 'void google::protobuf::RepeatedField<Element>::operator=(const google::protobuf::RepeatedField<Element>&) [with Element = int]' is private
[  117s] /home/abuild/rpmbuild/BUILD/libphonenumber-8.10.6/cpp/src/phonenumbers/phonenumberutil.cc:359: error: within this context

**Comment by daviddrysdale** [comment]
This is the wrong repo -- that looks like C++ code, which lives upstream at https://github.com/googlei18n/libphonenumber.  This repo is just for Python code.
