### ISSUE TITLE
How to create a phone number object without knowing country code

### ISSUE THREAD

**Issue by rahul-ve** [daviddrysdale/python-phonenumbers#145]
Hi,
I am trying to  validate some phone numbers, just need clarification on building the phone number object eg: ph.parse(phone_no_string, "AU"). I am in Australia.

We have numbers from across the globe in our database, there is no consistent format, we have: 

- international numbers with "+""country_code""number", 

- some with just "country_code""number", 

- some just "area_code""number" (local numbers) and 

- some just "fixed_line_number" (which are valid if dialed locally within the state), they are missing the area code, that is the reason for validation fail, which is fine. 

Now when building the phone number object, we can use "ZZ" if the number starts with "plus""country_code" but not all the numbers have that format, so how to build the phone number object with the right country code without knowing that in advance?

I have used "AU" for parsing all numbers as majority were from Australia, which actually yielded good results. Most of the international numbers parsed correctly because they were prefixed with "+" and geographical info was correct.  But I dont know if this is the correct approach. 
I am just trying to understand what the right approach should be. it would be great if someone can give me pointers on how to use this library. 

thanks, 
yudi

**Comment by daviddrysdale** [comment]
Phone numbers are not globally unique, so it's not possible to do what you're asking &ndash; the same sequence of digits can and does connect to different phones when dialled from different places.  So you either need to know the dialling country, or you need to have the phone number in a globally unique format ([E.164](https://en.wikipedia.org/wiki/E.164), with leading +).
