### ISSUE TITLE
Odd validation error

### ISSUE THREAD

**Issue by YuriFarias741** [daviddrysdale/python-phonenumbers#146]
I would like to understand why the number "+5534234234234" (Brazilian country code) isn't considered valid while other phones with the same pattern are fine.
![Seleção_149](https://user-images.githubusercontent.com/38434985/55358335-85a48700-54a5-11e9-830e-5f35cb654a6b.png)

**Comment by daviddrysdale** [comment]
The same problem reproduces upstream ([invalid](https://libphonenumber.appspot.com/phonenumberparser?number=%2B5534234234234) vs. [valid](https://libphonenumber.appspot.com/phonenumberparser?number=%2B5521997846630)) so please report there, as per the issue template.

Also, please don't report problems using screenshots &ndash; it makes the text un-copy-pasteable.
