### ISSUE TITLE
Request: add how to contribute

### ISSUE THREAD

**Issue by abdelouahabb** [daviddrysdale/python-phonenumbers#15]
i just wanted to add contribution (Algeria information) but dont find how, what i want to do is  to edit regular expressions and add region match (for fixed line), but found the file containing DZ that is Auto-generated file and i should not edit it.

**Comment by daviddrysdale** [comment]
Most of the content for the library comes from the upstream [libphonenumber project](https://code.google.com/p/libphonenumber/) so it's best to [contribute there](https://code.google.com/p/libphonenumber/issues/entry), and wait for the changes to trickle back downstream (which usually takes a couple of weeks).

**Comment by abdelouahabb** [comment]
thank you
but the original project is a java project?

**Comment by daviddrysdale** [comment]
It is, but the most important content is a big [XML file filled with regular expressions](https://code.google.com/p/libphonenumber/source/browse/trunk/resources/PhoneNumberMetaData.xml).  You can suggest a patch to that, or just let them know what numbers it's not coping with.

**Comment by abdelouahabb** [comment]
ah! thank you very much :)
