### ISSUE TITLE
Phonenumbers found in input text containing (say) dates

### ISSUE THREAD

**Issue by pallavi-xtage** [daviddrysdale/python-phonenumbers#164]
It is giving phone numbers as an output which is correct but also giving output of this type of data as well:- 2015 – 03/2016 Which we don't need. How to tackle with such case?

**Comment by daviddrysdale** [comment]
Please could you:
 - provide a specific failure example
 - confirm whether the upstream Java code gives the same result for the same inputs.

**Comment by pallavi-xtage** [comment]
Failure example is :-
when i have all text and no phone number in a text.Then if text has date like this then it returns output like that I have mentioned above.

Example:-
input=sourcing data from multiple data sources and including them in execution plans CA 03/2015 – 03/2016

for match in phonenumbers.PhoneNumberMatcher(input, "US"):
        phn = match.raw_string
        print(phn)

output=2015 – 03/2016

**Comment by daviddrysdale** [comment]
I get the same result:
```
  match: PhoneNumberMatch [85,99) 2015 – 03/2016
```
from the upstream Java code
```java
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
String input = "sourcing data from multiple data sources and including them in execution plans CA 03/2015 – 03/2016";
Iterator<PhoneNumberMatch> iterator = phoneUtil.findNumbers(input, "US").iterator();
while (iterator.hasNext()) System.out.println("  match: " + iterator.next().toString());
```
As this isn't specific to the Python port, please raise upstream.
