### ISSUE TITLE
Match a phone number without specifying region/country 

### ISSUE THREAD

**Issue by abd-ghreeb** [daviddrysdale/python-phonenumbers#166]
Is there a way to use phoneNumberMatcher to match any possible phone number in a text without having to consider specific country/region.

https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/phonenumbers/phonenumbermatcher.py#L458

**Comment by daviddrysdale** [comment]
I don't believe so.  Phone numbers aren't globally unique – the same sequence of digits can and does connect to different phones when dialled from different places – so a dialling-country is needed to get a fully-specified phone number (unless it's got a leading +).

**Comment by downdawn** [comment]
the same problem.so, why not get all?
