### ISSUE TITLE
RTL phone rendering issue.

### ISSUE THREAD

**Issue by infosrabah** [daviddrysdale/python-phonenumbers#168]
Hi,

Using Django 3.0 as a Framework, and python-phonenumbers to render phone numbers in Django template.

LTR work great, but when the web page is in RTL (Right to Left = Arabic langauge) there's an issue rendrering phone numbers.

Ex : Phone number : 0779537579
```python
parsed = phonenumbers.parse('0779537579', 'SA')
phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.NATIONAL)
```
-----
1) Phone rendering in LTR : 0779 53 75 79
2) Phone rendrering in RTL : 79 75 53 0779

Is there a workaround for this or an option to say that this is a RTL one ???, I'm I missing something ?

PS:if the phone number does't have a space it is well rendered in the tempalte, wich (the sapce) was made by the phonenumbers(PhoneNumberFormat.NATIONAL).

Amazing library
Hope to hear from you soon.

Thank you

**Comment by daviddrysdale** [comment]
Could you give more details of a reproduction scenario please?  I can't immediately reproduce (see below) but I'm not particularly familiar with locale-specific stuff.

```pycon
Python 3.7.5 (default, Oct 19 2019, 03:54:26) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, '')
'en_GB.UTF-8'
>>> import phonenumbers
>>> phonenumbers.__version__
'8.11.1'
>>> parsed = phonenumbers.parse('0779537579', 'SA')
>>> phonenumbers.is_valid_number(parsed)  # number not valid; different lib version?
False
>>> phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.NATIONAL)
'779537579'
>>> locale.setlocale(locale.LC_ALL, 'he_IL')  # the only RTL locale I could immediately find on my machine
'he_IL'
>>> phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.NATIONAL)
'779537579'
```

**Comment by infosrabah** [comment]
1) Sorry but the number was valid for a 'DZ' region, meaning 
<code>parsed = phonenumbers.parse('0779537579', 'DZ')</code>

but you can't see much rendering in python shell, I'm talking in browser using a RTL language (Arabic for example).

2) I didn't come-up with a workround changing spaces by the code of "&nbsp;" non beaking line space instead of spaces that are generated by phonenumbers, and it worked, here's how :

<code>parsed = phonenumbers.parse('0779537579', 'DZ')</code>
<code>formated_phone = phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.NATIONAL)</code>
<code>formated_phone = formated_phone.replace(" ", "\xa0")</code>

here's a screenshots before using my workarround :
LTR image wich is good : [https://ibb.co/k4QD9yC](url)
RTL image wich is not well rendered : [https://ibb.co/HxrWKhK](url)
Those are same numbers, but not the same rendering in the web page.
 
any suggestions about my workarround ??

thank you for the amazing library

**Comment by daviddrysdale** [comment]
The phonenumbers library isn't doing the RTL reversing, so I don't think we can fix your problem here.  

Changing from normal to non-breaking space seems like a reasonable workaround, but I don't know much about i18n so I'm not sure if there's a better way.

However, I don't think replacing `" "` with `"\xa0"` would be generally safe &ndash; it will depend on the string encoding whether that works or not.  Converting the string to Unicode and replacing with `\u00a0` is more likely to be encoding-safe, I think.  (You don't say what Python version or package version you're using, so it's hard to be specific.)

**Comment by infosrabah** [comment]
- Python 3.7.3 (Already unicode fully supported)
- python-phonenumbers 8.11.1

any thoughts  ???

**Comment by daviddrysdale** [comment]
Nothing different than above &ndash; the phonenumbers library doesn't do any text rendering or RTL reversing, so I think you need to investigate what does (or use your non-breaking space substitution workaround).
