### ISSUE TITLE
Geocoder Gives Empty CountryName in Python

### ISSUE THREAD

**Issue by varskaj** [daviddrysdale/python-phonenumbers#174]
For italian numbers there is no country name
```py
geocoder.country_name_for_number(phonenumbers.parse("+3936855554284"), 'en')
```
The above gives a empty string

But on the [JAVA DEMO](https://libphonenumber.appspot.com/phonenumberparser?number=%2B3936855554284)
Phone Number region | IT
-- | --

Ideally, the country name should be given as Italy in the above function

**Comment by daviddrysdale** [comment]
The Java demo [uses a different entrypoint](https://github.com/google/libphonenumber/blob/master/java/demo/src/com/google/phonenumbers/PhoneNumberParserServlet.java#L294-L295):
```Java
        String region = phoneUtil.getRegionCodeForNumber(number);
        appendLine("Phone Number region", region == null ? "" : region, output);
```

Comparing like-for-like entrypoints, the same results are emitted:
```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> x = phonenumbers.parse("+3936855554284")
>>> phonenumbers.region_code_for_number(x)
'IT'
```

By the way, the reason why `country_name_for_number` returns an empty string is given in the help text: "If it could be from many territories, nothing is returned"  &ndash; here, the number is valid in both `IT` and `VA`.

(Also, the Java equivalent to `geocoder.country_name_for_number` is actually [`private`](https://github.com/google/libphonenumber/blob/master/java/geocoder/src/com/google/i18n/phonenumbers/geocoding/PhoneNumberOfflineGeocoder.java#L66):
```Java
  private String getCountryNameForNumber(PhoneNumber number, Locale language) {
```
I should probably have made the equivalent Python method internal, but it's a bit late to do so now.)
