### ISSUE TITLE
8.12.9 sdist doesnt include LICENSE

### ISSUE THREAD

**Issue by jayvdb** [daviddrysdale/python-phonenumbers#176]
When updating the openSUSE package from 8.12.0 to 8.12.9, I noticed that the PyPI sdist tarball no longer includes the `LICENSE` file.

Oddly, the 8.12.9 tarball for phonenumberslite does include the `LICENSE` file.  Quite possibly this suggests that different versions of setuptools was used to build the sdist.

**Comment by jayvdb** [comment]
Proximate cause https://github.com/daviddrysdale/python-phonenumbers/pull/160 .
IMO while removing cruft is useful, the importance of `LICENSE` shouldnt be left to auto voodoo by setuptools unless there was a flag to explicitly fail the process if the LICENSE file wasnt included.  Explicit being better than implicit, at least for files as critical as the license.

**Comment by jayvdb** [comment]
It would also be nice if testwrapper.py was included in the sdist, as it is mentioned prominently as a good mechanism for testing the sdist.

**Comment by daviddrysdale** [comment]
Thanks for spotting; does #177 look like it will cover what you're after?
