### ISSUE TITLE
Puerto Rico

### ISSUE THREAD

**Issue by lmvdz** [daviddrysdale/python-phonenumbers#179]
Hey I couldn't open an issue on the Google repo...

But puerto rico country codes are not +1 according to Authy which uses e164 standards.

+1787 and +1989 are valid Puerto Rico country codes.

Can someone help me create the Pull Request for this?

**Comment by daviddrysdale** [comment]
This needs to be raised upstream I'm afraid.

It looks like the upstream project are no longer using GitHub issues to track things, but their [contributing page](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue) now gives a [link to a Google issue tracker](http://issuetracker.google.com/issues/new?component=192347) instead.

**Comment by lmvdz** [comment]
Thanks david
