### ISSUE TITLE
NumberParseException is not picklable

### ISSUE THREAD

**Issue by arnimarj** [daviddrysdale/python-phonenumbers#181]
Hi,

I noticed that `NumberParseException` is not picklable. It deviates from the `__init__` signature of `Exception`, which itself implements `__reduce__` s.t. only the `msg` argument is pickled. This program:

```python
import pickle
from phonenumbers.phonenumberutil import NumberParseException

error = NumberParseException(NumberParseException.TOO_SHORT_AFTER_IDD, 'hello world')
s = pickle.dumps(error)
again = pickle.loads(s)
```

produces the output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'msg'
```

Adding a `__reduce__` method to `NumberParseException` seems  to fix it:

```python
    def __reduce__(self):
        return (type(self), (self.error_type, self._msg))
```

**Comment by daviddrysdale** [comment]
Thanks for spotting (and suggesting the fix).
