### ISSUE TITLE
phonenumbers with Pyinstaller?

### ISSUE THREAD

**Issue by gitdjc** [daviddrysdale/python-phonenumbers#183]
So far I haven't succeeded in generating a working executable, with pyinstaller, of a program that uses phonenumbers. Has anyone accomplished this? How? I'd be grateful for help here, including in the form of wild suggestions.

A comprehensive method would be most welcome, of course. Thanks.

djc

**Comment by daviddrysdale** [comment]
Not really an issue with `phonenumbers`, I'm afraid (but do re-open with details if there's something specific about the `phonenumbers` package that's breaking pyinstaller)
