### ISSUE TITLE
Validation Issue For New Numbers 

### ISSUE THREAD

**Issue by bobozar** [daviddrysdale/python-phonenumbers#188]
I'm using this package https://github.com/stefanfoulis/django-phonenumber-field/ and the package relies on this package https://github.com/daviddrysdale/python-phonenumbers/ .

New numbers are being released in Nigeria and I would like it to be recognized. For example the new number is 

`+2349135700000`

When I tried adding that number I got the below in return as response.

`InvalidPhoneNumber(raw_input=+234913570000)`

Example of the result gotten from a recognized number after validation.

`PhoneNumber(country_code=234, national_number=8050000000, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None)`

I tried the number on http://libphonenumber.appspot.com/ and it validates fine on the site. To the extent of showing me the carrier of the phone number. 

Is there an update that needs to be done by your team? @daviddrysdale 

Kindly share your thoughts.

**Comment by daviddrysdale** [comment]
Looks like it already works in the current version, so maybe you need to update somewhere?

```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> phonenumbers.__version__
'8.12.16'
>>> x = phonenumbers.parse("+2349135700000", "")
>>> x
PhoneNumber(country_code=234, national_number=9135700000, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> phonenumbers.is_valid_number(x)
True
```

**Comment by bobozar** [comment]
Yeah, you are right. I just need to update. Thanks so much! You rock.
