### ISSUE TITLE
how are manage the version updates

### ISSUE THREAD

**Issue by inigoasensiorey** [daviddrysdale/python-phonenumbers#195]
We are using the library phonenumbers and we would like to ask you how you are managing the new versions. The thing is that we want to know how you change the version, for example, when you include new carriers in  the library.

**Comment by daviddrysdale** [comment]
Version updates are entirely driven by the upstream [libphonenumber](https://github.com/google/libphonenumber) project (and I keep version numbers in sync).   The upstream project is entirely responsible for metadata, including carrier data.

At some point after they release a new version, I update this repo to match:

- Copy the upstream [`resources/`](https://github.com/google/libphonenumber/tree/master/resources) directory into this repo
- [Regenerate all of the metadata Python files from the upstream metadata](https://github.com/daviddrysdale/python-phonenumbers/blob/dev/tools/python/makefile#L15-L55)
- Create a diff of the upstream Java code against the previous release to see if there are any code changes that need to be incorporated.
- Re-run all of the unit tests and check the code coverage remains at 100%
- [Release the new Python version to GitHub and PyPI](https://github.com/daviddrysdale/python-phonenumbers/tree/dev/tools/python#release-procedure).
