### ISSUE TITLE
PhoneNumberFormat: Not outputting specified formats.

### ISSUE THREAD

**Issue by SamuelMTDavies** [daviddrysdale/python-phonenumbers#196]
I have a list of GB numbers (some with leading zeros and some without.

I am trying to format them all to E164 format but phonenumbers.PhoneNumberFormat.INTERNATIONAL/E164/NATIONAL all output the same wrong results.

I can't replicate this on the JAVA web app which outputs the numbers correctly.

Code Block:
```
z = phonenumbers.parse(str(number), "GB")

    if phonenumbers.is_valid_number(z):

        phonenumbers.format_number(z, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
```

Actual Output:
`Country Code: 44 National Number: XXXXXXXXXX`

Expected Output:
` +44XXXXXXXXXX`

Am I missing something?

**Comment by daviddrysdale** [comment]
Works OK for me:
```pycon
Python 2.7.18 (default, Feb 27 2021, 08:40:44) 
>>> import phonenumbers
>>> number = "0800 800150"
>>> z = phonenumbers.parse(str(number), "GB")
>>> str(z)
'Country Code: 44 National Number: 800800150'
>>> if phonenumbers.is_valid_number(z):
...     phonenumbers.format_number(z, phonenumbers.PhoneNumberFormat.E164)
... 
u'+44800800150'
```

Are you sure the output you're seeing is going through `format_number` ?

**Comment by SamuelMTDavies** [comment]
> ```
> >>> import phonenumbers
> >>> number = "0800 800150"
> >>> z = phonenumbers.parse(str(number), "GB")
> >>> str(z)
> 'Country Code: 44 National Number: 800800150'
> >>> if phonenumbers.is_valid_number(z):
> ...     phonenumbers.format_number(z, phonenumbers.PhoneNumberFormat.E164)
> ```

I've run your code and the same issue I was experiencing happens - you are running python 2.7 whereas I am running 3.9. Could this make a difference?

Can you re-open the issue? The fact we run the same code and get different results is more than odd.

**Comment by SamuelMTDavies** [comment]
I've been trying to simplify and debug where its going wrong and when I remove the if statement I get the desired/expected result.

**Comment by daviddrysdale** [comment]
Happy to re-open the issue, but I get the same results with Python 3.9:
```pycon
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> number = "0800 800150"
>>> z = phonenumbers.parse(str(number), "GB")
>>> str(z)
'Country Code: 44 National Number: 800800150'
>>> if phonenumbers.is_valid_number(z):
...   phonenumbers.format_number(z, phonenumbers.PhoneNumberFormat.E164)
... 
'+44800800150'
```

**Comment by daviddrysdale** [comment]
What version of the phonenumbers library are you using?  (Not that it's likely to matter much, I don't think the code in `is_valid_number()` has changed for a long time)

**Comment by SamuelMTDavies** [comment]
I am using Version: 8.10.13

How do we go about narrowing it down any further?

**Comment by daviddrysdale** [comment]
That version is 2 years old, but still works for me:
```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> number = "0800 800150"
>>> z = phonenumbers.parse(str(number), "GB")
>>> str(z)
'Country Code: 44 National Number: 800800150'
>>> if phonenumbers.is_valid_number(z):
...   phonenumbers.format_number(z, phonenumbers.PhoneNumberFormat.E164)
... 
'+44800800150'
>>> phonenumbers.__version__
'8.10.13'
```

Not really sure how to progress &ndash; can you find the code for your local copy of the library and check it hasn't been modified somehow?  Also, can you try upgrading to a more recent version?

**Comment by daviddrysdale** [comment]
Also, maybe try stepping into those 2 lines of code with [`pdb`](https://docs.python.org/3/library/pdb.html)?

**Comment by SamuelMTDavies** [comment]
Ok So I upgraded and it has resolved - I think an old version was installed as I had an old version of py-phone-number-fmt installed that resolved phonenumbers to a lower version.
