### ISSUE TITLE
Norwegian Phone numbers are not validated properly

### ISSUE THREAD

**Issue by DS992** [daviddrysdale/python-phonenumbers#197]
Hi,

I am using the phonenumberslite package.

If you have a Norwegian phone number: +4749123456

And first parse this:

parsedNumber = phonenumbers.parse("+4749123456")

This returns: Country Code: 47 National Number: 49123456

This is correct

Then check if it's valid: phonenumbers.is_valid_number(pasedNumber)

The validation fails, even though this is a perfectly correct Norwegian phone number.

Here is how I test for Norwegian Phone numbers:

if re.match(r"(^[49]\d{7}$)|(^0047[49]\d{7}$)|(^\+47[49]\d{7}$)|(^47[49]\d{7}$)", phoneNumber):
    phoneNumber = "+47" + phoneNumber[-8:]

The above regex is a perfect regex for Norwegian phone numbers and works every time

**Comment by daviddrysdale** [comment]
This seems to be [reproducible with the upstream Java code](https://libphonenumber.appspot.com/phonenumberparser?number=%2B4749123456), so please report there as per the instructions.
