### ISSUE TITLE
Feature Request - dummy number to pass validation tests

### ISSUE THREAD

**Issue by MrBillium** [daviddrysdale/python-phonenumbers#199]
Testing with this library requires me to use real numbers  to pass validation. To test I often need more unique numbers and have to resort to using  a real number and increment 1 - this is a pain!

Suggestion: add a dummy test  prefix.
For US  the generally accepted dummy is 555 which is never used ( except in the movies). Make it still fail wrong digit count but  NOT fail lookup.

Then I can test away using 555 111 1111 and 555 111 1112 etc but 555 12345  will still fail.

I am about to roll my own version now but it would be a nice feature to have in the library

How about:
TestPatterns :     Dict of country_code: number_pattern  that when enabled always returns a valid number lookup.

  e. g.    TestPatterns= {"US": "555*******"  }

**Comment by daviddrysdale** [comment]
The library has an `example_number` feature that gives a valid example number for a region, but there's only one.

Being able to generate more examples might be a useful feature, but I'm afraid this Python port only tracks the functionality of the [upstream code](https://github.com/google/libphonenumber).. Maybe ask there? If they add the feature it will eventually make its way into the Python port too&hellip;

<hr/>

```pycon
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
>>> from phonenumbers import example_number
>>> help(example_number)
Help on function example_number in module phonenumbers.phonenumberutil:

example_number(region_code)
    Gets a valid number for the specified region.
    
    Arguments:
    region_code -- The region for which an example number is needed.
    
    Returns a valid fixed-line number for the specified region. Returns None
    when the metadata does not contain such information, or the region 001 is
    passed in.  For 001 (representing non-geographical numbers), call
    example_number_for_non_geo_entity instead.

>>> example_number("GB")
PhoneNumber(country_code=44, national_number=1212345678, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
```

**Comment by MrBillium** [comment]
Understood.

My workaround in form validator was trivial since I don't even call the
library

def validate_phone(self, field):
    try:
        # Eval test numbers in test mode
        if myconfig.testmode:
            if str(field.data).startswith('555'):
                # dummy number so just accept it without calling phonenumbers
                return field

    .............
