### ISSUE TITLE
A lot of metadata?

### ISSUE THREAD

**Issue by pickfire** [daviddrysdale/python-phonenumbers#206]
> The library includes a lot of metadata, potentially giving a significant memory overhead

How significant? Can there be numbers rather than saying "a lot"? I think it would be good to clarify it.

**Comment by daviddrysdale** [comment]
Feel free to send a pull request for the README file, if you'd like to see more quantitative numbers there &ndash; the metadata is held in the various `phonenumbers/*data/` subdirs.

**Comment by daviddrysdale** [comment]
On second thoughts, added a size mention in 0f6cbc65879218d6529e3024fe3f2ed3d22c7e2b
