### ISSUE TITLE
Sort out duplicate `setup.py` instances

### ISSUE THREAD

**Issue by daviddrysdale** [daviddrysdale/python-phonenumbers#209]
#7 added a top-level `setup.py` file to help pip cope with the code being in a subdirectory.

Need to check whether this is still needed.  If it is still required, then some mechanism to keep the two files in sync is needed.

**Comment by AA-Turner** [comment]
Per https://pip.pypa.io/en/stable/topics/vcs-support/#url-fragments, sub-dir installs now seem to be viable

A
