### ISSUE TITLE
Package started installing global-scope "tests" package

### ISSUE THREAD

**Issue by mgorny** [daviddrysdale/python-phonenumbers#216]
91abecb66b131a7fe139b3149e49c4eadbe00a3c has added "tests" to the list of installed global-scope packages. This is a very bad idea since it's not namespaced at all, and can collide with other packages.

If you need to install tests, please move them inside "phonenumbers" directory to avoid polluting the global namespace.

**Comment by daviddrysdale** [comment]
cc @AA-Turner

**Comment by daviddrysdale** [comment]
I've yanked the release I did yesterday (8.12.32).

**Comment by AA-Turner** [comment]
Sorry, I'll take the fall for this one - misunderstanding how `disutils` works.

The simplest solution is to revert the specific parts (see PR #217).

This goes back to the status-quo of only distributing tests + testwrapper via the sdist and not installing them. I guess I might ask if this is the desired scenario, as the only way the tests can be used by end users (it seems) is unzipping the sdist into a location on `sys.path`. Most other libaries seem either not to distribute their tests, or if they do to put them as a sub-package (e.g. `numpy.testing`). So the second option (after #217) may be to remove entirely. 

However I'm not sure how much this functionality is used (xref Chesterton's fence), and I've found at least one request for inclusion in the past (#176). The test files seem to have been included in the distribution from the first commit, as far as I can tell.

A

**Comment by daviddrysdale** [comment]
> Sorry, I'll take the fall for this one - misunderstanding how disutils works.

No worries, I misunderstood it too.

> The simplest solution is to revert the specific parts (see PR #217). 
> This goes back to the status-quo ...

SGTM

**Comment by daviddrysdale** [comment]
Should be fixed by #217 &ndash; thanks @AA-Turner for the quick response.
