### ISSUE TITLE
IR region numbers

### ISSUE THREAD

**Issue by jaross** [daviddrysdale/python-phonenumbers#22]
Hi
Can you check phone numbers like +9812168560, please? They are formated (INTERNATIONAL) as +98 12168560, so the NDC length is zero. Moreover, I suspect that it is invalid number for the IR region.
Best
js

**Comment by daviddrysdale** [comment]
The results for the Python version are consistent with the master upstream Java version (via http://libphonenumber.appspot.com/), with both saying this is a valid IR number.  If you think this is wrong, please raise a metadata issue against the master libphonenumber version.
