### ISSUE TITLE
We Need Docs 

### ISSUE THREAD

**Issue by Zaeem20** [daviddrysdale/python-phonenumbers#221]
I appreciate your hard work but there is a lot of functions and methods, this makes it slight tough to memorize it for beginners can make a doc for and host it on readthedocs.io

**Comment by daviddrysdale** [comment]
I'm not comfortable with the permissions that are needed for http://readthedocs.io, I'm afraid.

I've put the `pydoc` generated docs at https://daviddrysdale.github.io/python-phonenumbers/ though.

**Comment by jonesnc** [comment]
That link should be added to the README.

**Comment by daviddrysdale** [comment]
Yeah, that makes sense &ndash; do you want to send a PR?

**Comment by jonesnc** [comment]
Sure thing! I'll create a PR tonight when I get off work. Thanks for the quick response!
