### ISSUE TITLE
Dutch mobile numbers

### ISSUE THREAD

**Issue by omerhar3l** [daviddrysdale/python-phonenumbers#226]
Hey ! 

It appears that now dutch numbers are longer than it used to and the validation is failing due to TOO_LONG number - few examples for phone numbers - 
+3197010257218
+3197010257483
+3197010256684

```
x=phonenumbers.parse('+3197010256684')
phonenumbers.is_valid_number(x) == False
```
the Actual length now is 11 digits, while the possible is top 10

**Comment by daviddrysdale** [comment]
Reproduces [upstream](https://libphonenumber.appspot.com/phonenumberparser?number=%2B3197010256684)
