### ISSUE TITLE
is there any function to get exact metadata of geocoding

### ISSUE THREAD

**Issue by Zaeem20** [daviddrysdale/python-phonenumbers#228]
Will you please explain to me is there any function to get deep information about carrier location, which issue I opened #227 
maybe I am wrong because I find deep metadata of geolocation in resources/geocoding

please reply 
Regards
Durani Zaeem

**Comment by daviddrysdale** [comment]
See the help:
```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
>>> import phonenumbers.geocoder
>>> import phonenumbers.carrier
>>> help(phonenumbers.geocoder)
<snip>
>>> help(phonenumbers.carrier)
<snip>
```

Raw data comes from upstream:

- [carrier data](https://github.com/google/libphonenumber/tree/master/resources/carrier)
- [geocoding data](https://github.com/google/libphonenumber/tree/master/resources/geocoding)

(and is independent of each other)
