### ISSUE TITLE
Public function geocoder.region_code_for_country_code not in the .pyi file

### ISSUE THREAD

**Issue by mdesjardins** [daviddrysdale/python-phonenumbers#231]
Using python 3.8.12, phonenumbers 8.12.40

I would like to use the function `geocoder.region_code_for_number`, but I am getting mypy errors because it is not defined in geocoder.pyi. I *think* the function is intended to be public (it doesn't start with a leading underscore)? It'd be nice if it could be added to the pyi file so I wouldn't need to suppress the mypy warning.

I basically need to get the iso2 country code for a given phone number. If there's a better/more appropriate way to do that than using `geocoder.region_code_for_number`, then that would work, too!

Thank you! 🙏  And thanks for all your work!

**Comment by AA-Turner** [comment]
Not sure if you mean `_for_number` or `_for_country_code`, but both are part of `phonenumberutil`, not `geocoder`:

https://github.com/daviddrysdale/python-phonenumbers/blob/e75438338d70e33aee530a29960d2b0911dfb09f/python/phonenumbers/phonenumberutil.pyi#L167

https://github.com/daviddrysdale/python-phonenumbers/blob/e75438338d70e33aee530a29960d2b0911dfb09f/python/phonenumbers/phonenumberutil.pyi#L169

You can import them from geocoder as they're used locally in the module, but mypy is probably complaining as the canonical location isn't there. 

A

**Comment by mdesjardins** [comment]
Ahh! That might do the trick, thank you very much and sorry to bother you! :)
