### ISSUE TITLE
Update to PhoneNumberMetadata fixed_line national number pattern

### ISSUE THREAD

**Issue by Jorefice27** [daviddrysdale/python-phonenumbers#235]
Python 3.7.12
Phonenumbers 8.12.43

I currently have a use case which requires `+15823220881` to be recognized as a valid number (it is and is correctly verified by the java code). After some digging I was able to determine that the regex for `PhoneMetadata.metadata_for_region_or_calling_code("US", None).fixed_line` does not match, and the problem appears to be with the NXX (`232`) section of the number as `+15824005092` is properly verified using the python library. The 582 area code is a fairly new overlay area code for whatever that's worth, but it appears that the java library is working fine so hopefully this isn't a difficult change. If there is any additional information I can provide please let me know.

Thank you for the help!

**Comment by daviddrysdale** [comment]
I think this probably just needs a slightly more recent version of the code:
```pycon
>>> import phonenumbers
>>> phonenumbers.parse("+15823220881", None)
PhoneNumber(country_code=1, national_number=5823220881, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> x = phonenumbers.parse("+15823220881", None)
>>> phonenumbers.is_valid_number(x)
True
>>> phonenumbers.__version__
'8.12.45'
```

**Comment by Jorefice27** [comment]
Yep that was it. Didn't realize we were slightly behind. Thanks for catching that!
