### ISSUE TITLE
Colombian number validation failing

### ISSUE THREAD

**Issue by CharlieBGood** [daviddrysdale/python-phonenumbers#236]
python ---3.9
library ---3.0.1

I'm trying to validate the Colombian number '+573245901619' and the library keeps returning me an error. Is there any way to make this validation pass?

**Comment by daviddrysdale** [comment]
Although 3.0.1 is not a valid version for the library (the first release was 3.5b1 in 2011), I suspect the problem is that you have an old version &ndash; the current version parses that number fine.

```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
>>> import phonenumbers
>>> phonenumbers.__version__
'8.12.46'
>>> x = phonenumbers.parse("+573245901619")
>>> x
PhoneNumber(country_code=57, national_number=3245901619, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> phonenumbers.is_valid_number(x)
True
```
