### ISSUE TITLE
contry code conflect JM and US

### ISSUE THREAD

**Issue by skndrvoip** [daviddrysdale/python-phonenumbers#237]
i have problem with other contery start with 1
like Jmaica JM start with 1 and usa start with 1
my target Jmaica 1 876-xxx-xxx
but its recognize as US and it must JM
so any way to fix it ?

**Comment by daviddrysdale** [comment]
Jamaica is part of [NANPA](https://en.wikipedia.org/wiki/North_American_Numbering_Plan), as is the USA, so they both have numbers that start with **+1** (in E.164 notation).  However, various things (outside of this library) incorrectly assume that +1 is always/just USA.

The geocoder module for this library can distinguish though:

```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
>>> import phonenumbers
>>> x = phonenumbers.parse("+18767544742")
>>> x
PhoneNumber(country_code=1, national_number=8767544742, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> x.country_code
1
>>> import phonenumbers.geocoder
>>> phonenumbers.geocoder.country_name_for_number(x, "en")
'Jamaica'
>>> phonenumbers.geocoder.description_for_valid_number(x, "en")
'Jamaica'
```

**Comment by skndrvoip** [comment]
i use your library to recognize the proxy from phone number so when i use Jamaica phone number the proxy recognized it as US proxy while it must be Jamaican proxy so i want use in this case country_code JM not US

        pn = phonenumbers.parse('+' + str(phones[0]))
        cc = region_code_for_country_code(pn.country_code).lower()
        proxy_gen = f"ip:port:user-country-{cc}:pass"
        mylogs.info('Proxy : ' + proxy_gen)
+18767544742
so cc return US must JM
its just happend with countery start with +1

**Comment by daviddrysdale** [comment]
As per the help: 'In the case of multiple regions, the one designated in the metadata as the "main" region for this calling code will be returned.

```
Help on function region_code_for_country_code in module phonenumbers.phonenumberutil:

region_code_for_country_code(country_code)
    Returns the region code that matches a specific country calling code.
    
    In the case of no region code being found, UNKNOWN_REGION ('ZZ') will be
    returned. In the case of multiple regions, the one designated in the
    metadata as the "main" region for this calling code will be returned.  If
    the country_code entered is valid but doesn't match a specific region
    (such as in the case of non-geographical calling codes like 800) the value
    "001" will be returned (corresponding to the value for World in the UN
    M.49 schema).
```
