### ISSUE TITLE
parsing german (?) 7-digit mobile number not correctly

### ISSUE THREAD

**Issue by Moritz-Schmidt** [daviddrysdale/python-phonenumbers#238]
Country: Germany/DE
Example number(s) and/or ranges: 491845269411
issue on issuetracker.google.com: https://issuetracker.google.com/issues/229628558

python-version: 3.9.7
python-phonenumbers-version: 8.12.36

Authoritative evidence (e.g.national numbering plan, operator announcement): https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany

Link from demo showing error:http://libphonenumber.appspot.com/phonenumberparser?number=491845269411&country=DE

491845269411 should parse to country_code = 49, national_number = 1845269411 and not country_code = 49
national_number = 491845269411, the 49 is duplicated.

German Phone numbers without the national prefix always start with 0.
49 at the beginning of the number should not be assumed to be a number with the area code 049

**Comment by daviddrysdale** [comment]
I'll let upstream deal with this &ndash; when the fix arrives there, it will be incorporated here as part of the normal upstream merge process.
