### ISSUE TITLE
NumberParseException

### ISSUE THREAD

**Issue by asuvorov** [daviddrysdale/python-phonenumbers#24]
Hi.
I've got an exception "(0) Could not interpret numbers after plus-sign" when trying to save phone number like "2146491379" - it's an US phone number. The thing is that it happens only to phone numbers starting with "2" or "+2".

Request Method: POST
Request URL: http://10.1.0.2/admin/profiles/profile/2/
Django Version: 1.4.5
Exception Type:  NumberParseException
Exception Value: (0) Could not interpret numbers after plus-sign.
Exception Location: /.../.env/local/lib/python2.7/site-packages/phonenumbers/phonenumberutil.py in parse, line 2410
Python Executable: /usr/bin/python
Python Version: 2.7.3

Name: phonenumbers
Version: 5.7b2

**Comment by daviddrysdale** [comment]
I get the following output, which is what I'd expect (and the upstream [Java version](http://libphonenumber.appspot.com/) gives similar results.

``````
>>> import phonenumbers
>>> x = phonenumbers.parse("2146491379", "US")
>>> print x
Country Code: 1 National Number: 2146491379 Leading Zero: False
>>> x = phonenumbers.parse("+2146491379", "US")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmd/code/python-phonenumbers/python/phonenumbers/phonenumberutil.py", line 2410, in parse
    "Could not interpret numbers after plus-sign.")
phonenumbers.phonenumberutil.NumberParseException: (0) Could not interpret numbers after plus-sign.```
``````

In the second case, "+2146491379" looks like an international number (because of the leading plus) but doesn't have a valid country code.  If it's supposed to be a US number, it's missing the leading 1 (i.e. it should be "+12146491379").

Do you know what the exact parameters to parse are in your scenario?

**Comment by daviddrysdale** [comment]
Closing for now, please re-open if you still have problems.

**Comment by arnorhaux** [comment]
Hi 

phoneNumberUtil.Parse("+00000000000000", "IS"); gives me exception "Could not interpret numbers after plus-sign"

But online version is able to parse it -> https://libphonenumber.appspot.com/phonenumberparser?number=+00000000000000&country=IS 

Bear in mind that, I do not have information what is the correct countrycode, so IS is just the default.

**Comment by daviddrysdale** [comment]
@arnorhaux : this is unrelated, please raise a separate issue.
