### ISSUE TITLE
Redacting part of number

### ISSUE THREAD

**Issue by guilhermearaujo** [daviddrysdale/python-phonenumbers#240]
We've been using this lib to parse and format numbers, and eventually we need to also redact part of the number.

For instance, in BR phones formatted such as `+55 11 94444-0000`, I'd like to produce `+55 11 *****-0000`.

Right now I am using this piece of code:
```python
def redact_phone(phone: str) -> str:
    redact = lambda m: "*" * (len(m.group()) - 1) + "-"
    pattern = re.compile(r"(\d+)-")
    return pattern.sub(redact, phone)
```

The problem here is that it relies on the original formatted string containing a dash. I do not know whether this approach will work for every other country format, my intuition says _"most likely not"_.

So I'd like to propose a suggestions for this lib to implement a function, or maybe an argument in `format_number` that could take care of that.

In case this is out of the scope of the project, what files/resources can I read to understand a bit more the possibilities and how to make my function work with a broader number of formats?

**Comment by daviddrysdale** [comment]
This project is purely a Python clone of the [upstream Java codebase](https://github.com/google/libphonenumber), so making contact with the experts there would probably be the best approach. 

I think `format_by_pattern` is probably the closest thing in the existing API, but I suspect it would be too brittle to variance in formats between countries (in the same way as you point out above).

```pycon
>>> import phonenumbers
>>> x = phonenumbers.parse("+55 11 94444-0000", "")
>>> phonenumbers.format_by_pattern(x, phonenumbers.PhoneNumberFormat.INTERNATIONAL, [])
'+55 11944440000'
>>> phonenumbers.format_by_pattern(x, phonenumbers.PhoneNumberFormat.INTERNATIONAL, [phonenumbers.NumberFormat(pattern="(\\d{3})(\\d{3})(\\d{4,6})", format="\\1xxx\\3")])
'+55 119xxx40000'
```
