### ISSUE TITLE
missing 8.12.50 tag

### ISSUE THREAD

**Issue by arthurzam** [daviddrysdale/python-phonenumbers#243]
I'm Gentoo maintainer of `phonenumbers` python package, and we are using the github release tarballs for our package. We can see that `8.12.50` was released on PyPi, but not such tag have been created in this github repo.
Would it be possible to add the release tag.

**Comment by daviddrysdale** [comment]
[Done](https://github.com/daviddrysdale/python-phonenumbers/releases/tag/v8.12.50), not quite sure how I forgot that step this time around.

**Comment by arthurzam** [comment]
Thank you for the fast response 😄
