### ISSUE TITLE
Question regarding the 'isValid' method of this library.

### ISSUE THREAD

**Issue by Jimchoo91** [daviddrysdale/python-phonenumbers#244]
Could someone please give me a clear explanation of what the 'isValid' method does in this library? For example, if I input a number with a country, eg phonenumber.is_valid_number('+123949230', 'GB'). Does this check if this number meets the validity criteria for this country by checking the prefix and length of the number? How is this different from the is_possible number?

**Comment by daviddrysdale** [comment]
Best place to point you is https://github.com/google/libphonenumber/blob/master/FAQ.md#what-is-the-difference-between-ispossiblenumber-and-isvalidnumber, which references https://github.com/google/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2660-L2682
