### ISSUE TITLE
French fictitious phone number blocks fail the is_valid_number check

### ISSUE THREAD

**Issue by Lordnibbler** [daviddrysdale/python-phonenumbers#250]
French [fictitious phone number](https://en.wikipedia.org/wiki/Fictitious_telephone_number) block of `+33 6 39 98 xx xx` fails the `is_valid_number` check

```bash
$ python --version
Python 3.8.12

$ python -c "import phonenumbers; print(phonenumbers.__version__)"
8.12.56
```

```python3
(Pdb) phone_number
'+33639989098'
(Pdb) parsed = parse(phone_number, "FR")
(Pdb) parsed
PhoneNumber(country_code=33, national_number=639989098, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
(Pdb) is_valid_number(parsed)
False
```

**Comment by daviddrysdale** [comment]
As per instructions: 
 
> Before reporting an issue with parsing particular numbers, check if the problem also occurs with the online version of the Java code at <https://libphonenumber.appspot.com/>

<https://libphonenumber.appspot.com/phonenumberparser?number=%2B33639989098&country=FR>

**Comment by Lordnibbler** [comment]
@daviddrysdale is the upstream https://github.com/google/libphonenumber?

**Comment by daviddrysdale** [comment]
Yes, that's the upstream project.  The [metadata](https://github.com/google/libphonenumber/tree/master/resources) and the [Java code](https://github.com/google/libphonenumber/tree/master/java/libphonenumber/src/com/google/i18n/phonenumbers) there are the source-of-truth for this Python port &ndash; fixes need to go there and flow downstream to here.
