### ISSUE TITLE
Carrier Name not returning

### ISSUE THREAD

**Issue by faris-hasan** [daviddrysdale/python-phonenumbers#252]
Hello all,
I am using "phonenumbers 8.12.57", I am getting almost every carrier names but if I am entering a mobile number "+13106663987" and "+13106669163" or any same particular numbers it is not returning carrier name. Your Help would be really appreciated. 
Thank You :)

**Comment by daviddrysdale** [comment]
There doesn't [appear](https://libphonenumber.appspot.com/phonenumberparser?number=%2B13106663987) to be any [carrier metadata](https://github.com/google/libphonenumber/blob/master/resources/carrier/en/1.txt) in the upstream project for numbers starting "+1310...", so nothing we can do here &ndash; try asking upstream.
