### ISSUE TITLE
Not getting carrier name of US numbers

### ISSUE THREAD

**Issue by nabeel-dev1340** [daviddrysdale/python-phonenumbers#253]
It always give a blank output when getting the carrier name of US numbers, someone please look into it.
It works for the other countries but not for US.

**Comment by masterseo2000** [comment]
Yes I am running into the same issue

**Comment by daviddrysdale** [comment]
The metadata for carrier information comes from [this file](https://github.com/google/libphonenumber/blob/master/resources/carrier/en/1.txt) in the [upstream libphonenumber project](https://github.com/google/libphonenumber), which covers [NANPA](https://en.wikipedia.org/wiki/North_American_Numbering_Plan) numbers.

Looking at the contents of that file, it seems like there's generally only carrier data for non-US countries under NANPA, and if there's no metadata available then the library (whether upstream Java or Python here) can't return an answer.

(I'd *guess* that the structure of US area codes means that an (offline) mapping from number to carrier isn't possible, but asking the upstream project might give a more definitive answer.)
