### ISSUE TITLE
Prefix at RFC 3966

### ISSUE THREAD

**Issue by KristjanESPERANTO** [daviddrysdale/python-phonenumbers#256]
Why do I get a 'tel:' prefix with RFC 3966, but not with all other variants? That seems inconsistent to me.

```python
>>> phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.RFC3966)
'tel:+44-20-8366-1177'
>>> phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.NATIONAL)
'020 8366 1177'
>>> phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
'+44 20 8366 1177'
>>> phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.E164)
'+442083661177'
```

My system:
```bash
$ python --version
Python 3.9.2

$ python -c "import phonenumbers; print(phonenumbers.__version__)"
8.13.2
```

**Comment by daviddrysdale** [comment]
[RFC3966](https://www.rfc-editor.org/rfc/rfc3966) describes how to encode telephone numbers as [URIs](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier); to do that, it uses a "[scheme](https://en.wikipedia.org/wiki/List_of_URI_schemes)" prefix of `tel:`.  In other words, the `tel:` prefix is the equivalent to the `http:` or `https:` prefix for web addresses.

**Comment by KristjanESPERANTO** [comment]
Thanks for the explanation! :slightly_smiling_face:
