### ISSUE TITLE
Is it possible to know phone number type?

### ISSUE THREAD

**Issue by p1xel007** [daviddrysdale/python-phonenumbers#258]
I'm currently using the PHP port of this package and I can see if a phone number is landline or mobile. 
https://github.com/Propaganistas/Laravel-Phone

Is it possible to achieve the same with this package?

**Comment by daviddrysdale** [comment]
It's only possible to distinguish mobile from landline for some regions:

- Some regions (e.g. US) use the same numbering space for both fixed line and mobile, so only `FIXED_LINE_OR_MOBILE` can be returned.
- Some regions (e.g. UK) use distinct numbering spaces for `FIXED_LINE` and `MOBILE` and so the two can be distinguished.

See #49 for more discussion.
