### ISSUE TITLE
Fuzzing python-phonenumbers on OSS-Fuzz

### ISSUE THREAD

**Issue by rikfie** [daviddrysdale/python-phonenumbers#260]
Hi there, 

Are you interested to get python-phonenumbers fuzzed*? I have [written a harness](https://github.com/rikfie/python-phonenumbers-fuzzer) for python-phonenumbers and it's ready to be integrated. Many libraries (including [libphonenumber](https://github.com/google/oss-fuzz/tree/master/projects/libphonenumber)) are being fuzzed on [OSS-Fuzz](https://github.com/google/oss-fuzz) and I would like to add python-phonenumbers. 

The only condition for fuzzing on OSS-Fuzz is that any bugs found must be fixed and released within 90 days; the bug will be publicly disclosed past this point.

If you're interested, please provide me with an e-mail addresses of a maintainer(s). The e-mail addresses must be linked to a Google account. Note that the addresses will be stored in a public repository. If this is not an option, I can forward bug reports to you.

\* Fuzz testing is a well-known technique for uncovering programming errors in software. OSS-Fuzz aims to make common open source software more secure and stable by combining modern fuzzing techniques with scalable, distributed execution.

**Comment by daviddrysdale** [comment]
Yes, setting up OSS-Fuzz for the project (with maintainer `drysdale@google.com`) would be great &ndash; many thanks.

**Comment by rikfie** [comment]
Just to keep you updated: the fuzzer has been accepted and integrated in OSS-Fuzz (a week ago), but not yet build.

**Comment by daviddrysdale** [comment]
AIUI this is up and running now.
