### ISSUE TITLE
Phone Number parsing incorrectly

### ISSUE THREAD

**Issue by da-tai** [daviddrysdale/python-phonenumbers#261]
Python version - 3.7.0
Phonenumbers version - 8.13.3

The first attempt with + gives an incorrect parse, while without + gives a correct parse.

Trying to parse - +6475052806 Country = CA
Result - `Country Code = 64
National Number = 75052806`

Parsing without +
Result - `Country Code = 1 National Number = 6475052806`

https://libphonenumber.appspot.com/phonenumberparser?number=+6475052806&country=CA

**Comment by daviddrysdale** [comment]
The Python code is giving the same answer as the Java code for +6475052806: https://libphonenumber.appspot.com/phonenumberparser?number=%2B6475052806&country=CA.

The URL <https://libphonenumber.appspot.com/phonenumberparser?number=+6475052806&country=CA> above is not correct: the plus character needs to be URL-encoded (as %2B) or it will be encoded as a space.

A phone number that starts "+64..." is (correctly) treated as an E.164 number from New Zealand.
