### ISSUE TITLE
Customize pattern for a region

### ISSUE THREAD

**Issue by ZahraMatinfar** [daviddrysdale/python-phonenumbers#262]
Hi
Is it possible to customize phone number patterns for a specific region?
I have some valid mobile numbers but the package raises errors that they are invalid. I checked patterns which are used for my specific region and I want to customize some of them.

**Comment by daviddrysdale** [comment]
Possible? Yes. Sensible? No. :-)

The source-of-truth for the phonenumber metadata comes from the [upstream libphonenumber project](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml), and there's a code generation step that emits [corresponding Python files here](https://github.com/daviddrysdale/python-phonenumbers/tree/dev/python/phonenumbers/data).

So if you really wanted to, you could replace or override that autogenerated code.  But a better way would be to report missing / incorrect patterns to the upstream project (ideally with evidence of use and examples).  They update their metadata regularly and those updates would then flow into this Python library on the next release.

(It's also worth checking that you have the most recent version of the library &ndash; if there's been a recent numbering change in the region, the latest version may already have the update.)
