### ISSUE TITLE
brazil number encountered as invalid even though the client claims it is

### ISSUE THREAD

**Issue by ShacharRatzabi** [daviddrysdale/python-phonenumbers#267]
The number:
+555499042452

it doesn't pass this line:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/100077308/222887557-a7e98bbf-451d-4930-a858-ae9cb5e18990.png">

checked it on libphonenumber.appspot.com ([here](https://libphonenumber.appspot.com/phonenumberparser?number=%2B555499042452&country=BR)), seems like its "is possible number: true" but "is valid: false".
can you help me check & fix that?

<img width="371" alt="image" src="https://user-images.githubusercontent.com/100077308/222887825-32575d32-f4bd-40c9-b634-212abb6beb29.png">

**Comment by daviddrysdale** [comment]
> If the same problem is visible with the Java code, report the problem upstream not here.
