### ISSUE TITLE
Support for ISO3166-1 country codes

### ISSUE THREAD

**Issue by keomabrun** [daviddrysdale/python-phonenumbers#269]
> Include Python version (`python --version`)

`3.10.5`

> Include library version (`python -c "import phonenumbers; print(phonenumbers.__version__)"`)

`8.13.9`

Hi :wave: 
Thanks for the work !

I am trying to parse a 3 digit ISO3166-1 country code for Great Britain and I can't make it work :(

Here is what I tried:
```python
phonenumbers.region_code_for_country_code(826)
```
Where 826 is the ISO3166-1 country code for GB: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
I was expecting to get "GB" as result, but I am getting "ZZ".

Maybe I am looking at the wrong file, but I cannot find the 826 country code:
https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/phonenumbers/data/__init__.py

I see that this is not the only code missing, so maybe this lib is not meant to follow the ISO3166 codes ?

Thank you,

**Comment by daviddrysdale** [comment]
Wrong sort of country code I'm afraid &ndash; as per the [help](https://daviddrysdale.github.io/python-phonenumbers/#-region_code_for_country_code) this is for a [country *calling* code](https://en.wikipedia.org/wiki/List_of_country_calling_codes):
```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
>>> import phonenumbers
>>> phonenumbers.region_code_for_country_code(44)
'GB'
```

**Comment by keomabrun** [comment]
Thank you @daviddrysdale  for the swift answer, I guess I'll have to use another lib then :) 
Have a nice day :wave:
