### ISSUE TITLE
Dutch public services numbers: eg. 140418

### ISSUE THREAD

**Issue by AlexionCRM** [daviddrysdale/python-phonenumbers#271]
In The Netherlands we have special "public services numbers", starting with 14
- eg. 140418
- Is there an option to allow these numbers?

NB This number can't be dialed from outside The Netherlands, so somethin like this +31140418 is NOT available.

**Comment by daviddrysdale** [comment]
Looks like it mostly works already (as a "universal access number" (UAN)), both here:

```pycon
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
>>> import phonenumbers
>>> x = phonenumbers.parse("140418", "NL")
>>> x
PhoneNumber(country_code=31, national_number=140418, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> phonenumbers.is_valid_number(x)
True
>>> numtype = phonenumbers.number_type(x)
>>> phonenumbers.PhoneNumberType.to_string(numtype)
'UAN'
```

and [upstream](https://libphonenumber.appspot.com/phonenumberparser?number=140418&country=NL).

What are you finding doesn't work?

**Comment by AlexionCRM** [comment]
Hi David, I'll have my colleague look into it, seems ok :-)

They will look into it in July (very busy with stuff now)

**Comment by AlexionCRM** [comment]
...
