### ISSUE TITLE
Error parsing phone numbers with double leading 1's

### ISSUE THREAD

**Issue by etekin-amfam** [daviddrysdale/python-phonenumbers#277]
I am using phonenumberslite 8.13.16, and noticed that when I parse a US code in the format 1(1XX)YYY-YYYY, the national number is parsed incorrectly as XXYYYYYYY instead of 1XXYYYYYYY. This does seem to be present in the Java version as well, see [1(123)4567890](https://libphonenumber.appspot.com/phonenumberparser?number=1%28123%29456-7890&country=US) , which is parsed incorrectly, vs [1(223)4567890](https://libphonenumber.appspot.com/phonenumberparser?number=1%28223%29456-7890&country=US), which is parsed incorrectly.

```python
import phonenumbers as pn
wrong_no = pn.parse('11234567890', region='US') #wrong
correct_no = pn.parse('12234567890', region='US') #correct
```

Putting a `+` sign in front does resolve the issue:
```python
correct_no = pn.parse('+11234567890', region='US') #correct
```

I have noticed the issue using python 3.9 and 3.10.

**Comment by MrMineev** [comment]
The phone number "1 (123) 456 7890" is invalid. The phone US phone numbers have this syntax 1(NXX) NXX-XXXX, where N represents any digit from 2 to 9, and X represents any digit from 0 to 9. (https://www.quora.com/What-is-the-American-mobile-phone-number-format) (https://en.wikipedia.org/wiki/North_American_Numbering_Plan)

**Comment by etekin-amfam** [comment]
> The phone number "1 (123) 456 7890" is invalid. The phone US phone numbers have this syntax 1(NXX) NXX-XXXX, where N represents any digit from 2 to 9, and X represents any digit from 0 to 9. (https://www.quora.com/What-is-the-American-mobile-phone-number-format) (https://en.wikipedia.org/wiki/North_American_Numbering_Plan)

That is true, but the code does not raise an Exception, just returns an incorrectly parsed number, so it is still an issue as the downstream code has no way of knowing the number was incorrect. Furthermore, if you do enter +11234567890, it does not complain that it is an invalid number.

**Comment by daviddrysdale** [comment]
The Python code is behaving the same as the upstream Java code here, so any requested/suggested changes to behaviour should be reported upstream.
