### ISSUE TITLE
Update the description for a number starting with +1737

### ISSUE THREAD

**Issue by wojcikstefan** [daviddrysdale/python-phonenumbers#28]
According to Wikipedia ( http://en.wikipedia.org/wiki/Area_codes_512_and_737 ):

> To relieve telephone exchanges in the Austin area, area code 737, overlying 512, went into effect in July 2013.

This could be updated:

```
In [2]: phonenumbers.description_for_number(phonenumbers.parse('+17375555555'), 'en')
Out[2]: ''

In [3]: phonenumbers.description_for_number(phonenumbers.parse('+15125555555'), 'en')
Out[3]: u'Texas'
```

**Comment by daviddrysdale** [comment]
The Python code gets metadata from the upstream [libphonenumber](https://code.google.com/p/libphonenumber/) project, so could you [report](https://code.google.com/p/libphonenumber/issues/list) this there please?
