### ISSUE TITLE
Carrier names for US numbers returning null

### ISSUE THREAD

**Issue by EmirIsKing** [daviddrysdale/python-phonenumbers#288]
Python 3.11.4
phonenumbers 8.13.27

I am trying to find carrier name for a US phone number and its returning null
I tried the number on an online platform https://www.numlookup.com/ and the number was valid

>>> import phonenumbers
>>> from phonenumbers import carrier
>>> ro_number = phonenumbers.parse("+40721234567", "RO")
>>> carrier.name_for_number(ro_number, "en")
'Vodafone'
>>> ro_number = phonenumbers.parse("+19013485864", "US")
>>> carrier.name_for_number(ro_number, "en")
''

**Comment by daviddrysdale** [comment]
Python results match [upstream results](https://libphonenumber.appspot.com/phonenumberparser?number=%2B19013485864&country=US) so this is not an issue specific to the Python version.
