### ISSUE TITLE
Inconsistent parsing for Gabon phone numbers

### ISSUE THREAD

**Issue by S64E4-5SWIN-ER333** [daviddrysdale/python-phonenumbers#289]
Python 3.11.6
phonenumbers 8.13.30

Since 2019, Gabon changed their international phone number format: 

![image](https://github.com/daviddrysdale/python-phonenumbers/assets/133607284/db68c8ca-c6a1-4c54-b957-a40c30af0572)

But when parsing Gabonese phone numbers through this library, +241 02 47 48 49 and +241 2 47 48 49 are considered two different results, while on the main Google library, they're both converted to +241 2 47 48 49.

Is this the intended behavior?
Thanks

**Comment by daviddrysdale** [comment]
https://libphonenumber.appspot.com/phonenumberparser?number=%2B241+02+47+48+49&country=ZZ differs from https://libphonenumber.appspot.com/phonenumberparser?number=%2B241+2+47+48+49&country=ZZ with the upstream library, and both match the current Python output.
