### ISSUE TITLE
Region FR national_number_pattern requires an update

### ISSUE THREAD

**Issue by wbwlkr** [daviddrysdale/python-phonenumbers#290]
Hello @daviddrysdale,

This is my first contribution of your library, I would like to warn you that there is an update to be done in this line  : 
https://github.com/daviddrysdale/python-phonenumbers/blob/0eaa2db8f62c722bcfb7ca9bffd7bb95a6afe33b/python/phonenumbers/data/region_FR.py#L7

The regex of `national_number_pattern` is 
'(?:**6**(?:[0-24-8]\\d|3[0-8]|9[589])|7[3-9]\\d)\\d{6}'.
A french mobile number can start with "+336" but also "+337", then the regex needs to be updated to
'(?:**[6-7]**(?:[0-24-8]\\d|3[0-8]|9[589])|7[3-9]\\d)\\d{6}'.

Currently, **all the french mobile numbers starting with +337 are not validated**, for example "+33721397536".

The validator of your library is used by @stefanfoulis's django library https://github.com/stefanfoulis/django-phonenumber-field

**Can I help you ** in order to fasten the release of the patch ? 

Best regards to both of you

**Comment by daviddrysdale** [comment]
The `data/region_FR.py` file is generated from the `resources/PhoneNumberMetadata.xml` file, which in turn is copied from the upstream libphonenumber project.  

So you should [report this as a metadata issue upstream](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue).

**Comment by wbwlkr** [comment]
The number "+33749004284" works anyway, thank you for your time.
