### ISSUE TITLE
Phonenumbers don't work with italian numbers

### ISSUE THREAD

**Issue by lud50** [daviddrysdale/python-phonenumbers#296]
loc = phonenumbers.geocoder.description_for_number(cnum, "IT")
this formula return a empty string vwn is used with an italian number

**Comment by daviddrysdale** [comment]
Works for me:
```pycon
Python 3.11.7 (main, Dec  9 2023, 06:23:53) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> phonenumbers.__version__
'8.13.38'
>>> cnum = phonenumbers.parse("(+39) 06.3691.8899", "IT")
>>> import phonenumbers.geocoder
>>> phonenumbers.geocoder.description_for_number(cnum, "IT")
'Rome'
```

Please provide an example of failure, along with a link to the upstream Java code being successful for the same inputs.

**Comment by lud50** [comment]
Yes, but this is a fixed number not a mobile number and in italy the prefix
of fixed number refers a large zone.

Il lun 10 giu 2024, 18:36 David Drysdale ***@***.***> ha
scritto:

**Comment by daviddrysdale** [comment]
This sounds like a metadata issue, which should be dealt with upstream.
