### ISSUE TITLE
Need an i18n enhancement for error text

### ISSUE THREAD

**Issue by BrentHuang** [daviddrysdale/python-phonenumbers#298]
```
try:
    z = pn.parse(phonenumber, 'CN')
    res = pn.is_possible_number_with_reason(z)
    if res != pn.ValidationResult.IS_POSSIBLE:
        error_text = pn.ValidationResult.to_string(res)
except pn.NumberParseException as exc:
    error_text = str(exc)
```

I need Simplified Chinese for 'str(exc)' and 'ValidationResult.to_string(res)', please. 

As fact, we need an i18n enhancement.

**Comment by daviddrysdale** [comment]
The Python code is based on the [upstream Java code](https://github.com/google/libphonenumber), so any change to how exceptions are formatted would need to come from there.

However, exceptions are consumed by code, not humans, so should probably not be translated.
