### ISSUE TITLE
code in Belarus

### ISSUE THREAD

**Issue by RazieL-hub** [daviddrysdale/python-phonenumbers#301]
Hello!
There are 3 operator codes in Belarus - life (25), mts (33, 29), a1 (29, 44)
Now, i can try validate
parsed_number = phonenumbers.parse('+375251234567')
print(phonenumbers.is_valid_number(parsed_number))
i have False, but i don't understand - WHY:D?

**Comment by daviddrysdale** [comment]
Python results are consistent with [upstream](https://libphonenumber.appspot.com/phonenumberparser?number=%2B375251234567&country=ZZ)

**Comment by pn** [comment]
Hello @RazieL-hub, please report your issue upstream, you can read how to create issue [here](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md).
