### ISSUE TITLE
Issues with retrieving packages on Arch linux

### ISSUE THREAD

**Issue by ERedstone** [daviddrysdale/python-phonenumbers#302]
`[eight@eightpc Mr.Holmes]$ sudo pacman -S python-phonenumbers
resolving dependencies...
looking for conflicting packages...

Package (1)                New Version  Net Change

extra/python-phonenumbers  8.13.45-1     62.29 MiB

Total Installed Size:  62.29 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 python-phonenumbers-8.13.45-1-any is up to date
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from london.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from archlinux.thaller.ws : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from mirror.ufscar.br : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from mirror.theash.xyz : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from america.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from mirror.moson.org : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from br.mirrors.cicku.me : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst' from es.mirrors.cicku.me : The requested URL returned error: 404
error: failed retrieving file 'python-phonenumbers-8.13.45-1-any.pkg.tar.zst.sig' from gb.mirrors.cicku.me : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.`

**Comment by daviddrysdale** [comment]
You need to raise this elsewhere &ndash; this repo isn't involved in that packaging format (just PyP).
