### ISSUE TITLE
Ecuador cellphone is treated as invalid

### ISSUE THREAD

**Issue by jaysonsantos** [daviddrysdale/python-phonenumbers#31]
As in how to call abroad [1] to call ecuador numbers, you have to use a 9 after country code and before area code + number. However phone numbers is reporting a cell phone number as invalid.
- phonenumbers.is_valid_number(phonenumbers.parse('+5936760xxxx)) == True
- phonenumbers.is_valid_number(phonenumbers.parse('+59396760xxxx')) == False # 593 **9** 6760xxxx

[1] http://www.howtocallabroad.com/ecuador/

**Comment by daviddrysdale** [comment]
The [Java version](http://libphonenumber.appspot.com/) appears to give the same results, so if this is a problem it's not specific to the Python version -- could you [report it upstream](https://code.google.com/p/libphonenumber/issues/list) rather than here please?

**Comment by jaysonsantos** [comment]
Reporting, thank you.
