### ISSUE TITLE
wrong parsing of russian number starting with 00

### ISSUE THREAD

**Issue by xrmx** [daviddrysdale/python-phonenumbers#32]
So that the country code is kept into the national number

> > > phonenumbers.parse("+7 894 123 45 67", "RU")
> > > PhoneNumber(country_code=7, national_number=8941234567, extension=None, italian_leading_zero=False, number_of_leading_zeros=None, country_code_source=None, preferred_domestic_carrier_code=None)
> > > 
> > > phonenumbers.parse("007 894 123 45 67", "RU")
> > > PhoneNumber(country_code=7, national_number=78941234567, extension=None, italian_leading_zero=True, number_of_leading_zeros=2, country_code_source=None, preferred_domestic_carrier_code=None)

**Comment by daviddrysdale** [comment]
I can reproduce this with the [upstream Java version](http://libphonenumber.appspot.com/), so could you report the problem [there](https://code.google.com/p/libphonenumber/issues/entry) please?

Thanks!

**Comment by xrmx** [comment]
Filed here:
https://code.google.com/p/libphonenumber/issues/detail?id=430&thanks=430&ts=1393576171

**Comment by daviddrysdale** [comment]
Ah, the upstream folk are the experts on the metadata and they point out that 00 isn't the international dialling code for calling from Russia.

But commit 65e01b2a3b6309b improves the Python README to make the need for country-dialled-from clearer.
