### ISSUE TITLE
setup.py test failed on kubuntu 12.04

### ISSUE THREAD

**Issue by netvigator** [daviddrysdale/python-phonenumbers#35]
I have been asked to use python-phonenumbers for a project.

I downloaded the zip, extracted to a directory, and ran 

python setup.py test

The tail end of the long list of errors is as follows:

begin quote
# '''
## FAIL: testParseNumbersWithPlusWithNoRegion (tests.phonenumberutiltest.PhoneNumberUtilTest)

Traceback (most recent call last):
  File "/home/Common/python-phonenumbers-dev/python/tests/phonenumberutiltest.py", line 2074, in testParseNumbersWithPlusWithNoRegion
    self.assertEqual(NZ_NUMBER, phonenumbers.parse("tel:03-331-6005;phone-context=+64", "ZZ"))
AssertionError: PhoneNumber(country_code=64, national_number=33316005, extension=None, italian_leading_zero=False, number_of_leading_zeros=None, country_code_source=None, preferred_domestic_carrier_code=None) != PhoneNumber(country_code=64, national_number=33316005, extension=None, italian_leading_zero=True, number_of_leading_zeros=None, country_code_source=None, preferred_domestic_carrier_code=None)

---

Ran 516 tests in 1.431s

FAILED (failures=50, errors=306)
'''

end quote

Maybe python-phonenumbers depends on something I have not installed yet.

I will be moving to kubuntu 14.04 in the near future.

I would appreciate a suggestion on what to do next.

Thanks,

netvigator aka Rick Graves

**Comment by daviddrysdale** [comment]
Hmm, I don't use the setup.py test target so there's probably some path issues -- I'll take a look.

In the meanwhile, if you run `./testwrapper.py` does it run OK?

**Comment by netvigator** [comment]
I tried ./testwrapper.py and it doesrun OK.

I had run python setup.py test from the directory above python.

So is everything OK?

Thanks,

**Comment by daviddrysdale** [comment]
Yeah, it's OK, it's just that the `setup.py test` way of invoking the tests doesn't pull in the fake metadata, so almost all the tests fail.

I've fixed in commit 253aa696111, which will show up when the next release happens
