### ISSUE TITLE
Mobile number start with 8 or 7 Handle

### ISSUE THREAD

**Issue by manti** [daviddrysdale/python-phonenumbers#36]
- [ ] Phone number start with 8 is not mapped to Mobile number ( Indian Mobile number)
- [ ] Phone number start with 7 is not mapped to Mobile number ( Indian Mobile number)

**Comment by daviddrysdale** [comment]
This sounds like a potential metadata issue.  Could you check whether the upstream Java code has the same issue (e.g. by entering example numbers into the [online parser](http://libphonenumber.appspot.com/)) and if so [raise the problem](https://code.google.com/p/libphonenumber/issues/entry) there instead?
