### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by codeinthehole** [daviddrysdale/python-phonenumbers#37]
It would be useful to know what changes between versions released to PyPI (without browsing commits). Would it be possible to keep a simple changelog that lists the changes between versions?

I ask as [django-oscar](https://github.com/tangentlabs/django-oscar) depends on this package and it's tricky to know what range of versions to support.

Thanks!

**Comment by daviddrysdale** [comment]
The `python/HISTORY` file only had minimal info, so I've done a quick retrospective update (in commit 317b0b128162b031e156b) to pull across more information from the [upstream changelog](https://code.google.com/p/libphonenumber/source/browse/trunk/debian/changelog).  I'll attempt to keep that in sync from now on.
