### ISSUE TITLE
Phone number length

### ISSUE THREAD

**Issue by marcelosalloum** [daviddrysdale/python-phonenumbers#42]
Hi guys,

is that a built-in way to limit the phone number length? Because I enter numbers with 20 chars and they are accepted by the validator, although I believe there are no phone numbers that big.

Thanks

**Comment by marcelosalloum** [comment]
BTW, according to the international telecom pattern [E.164](http://en.wikipedia.org/wiki/E.164), the total amount of numbers should be 15 at maximum.

**Comment by daviddrysdale** [comment]
A PhoneNumber object will have a national-significant-number part that's limited to 17 chars, plus up to 3 chars of country code (but it can have a long extension attached too).

The [upstream source](https://code.google.com/p/libphonenumber/source/browse/trunk/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#72) notes for this limit of 17 that: "The ITU says the maximum length should be 15, but we have found longer numbers in Germany".

Additionally, an E164 number can get prefixed with an international dialling code (e.g 011) and suffixed with an extension, and might have all sorts of other punctuation embedded (e.g. "001-(900) 234-5678 extension 123456") -- so a user-input phone number field can potentially be a lot longer than 17+3.

As a result the [internal limit](https://code.google.com/p/libphonenumber/source/browse/trunk/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#78) is 250 characters, but I don't know of any other limits.
