### ISSUE TITLE
parsing result doesn't match with libphonenumber.googlecode.

### ISSUE THREAD

**Issue by ywang-va** [daviddrysdale/python-phonenumbers#44]
number '01386000' with country code 'DE', should be a  valid number, however 

```
import phonenumbers
phone_obj = phonenumbers.parse('0138 6000', 'DE')
assert not phonenumbers.is_valid_number(phone_obj)
```

http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html

![screen shot 2014-07-14 at 11 32 39 pm](https://cloud.githubusercontent.com/assets/2091016/3580937/8531a15c-0be1-11e4-8f31-b16fb5c38222.png)

**Comment by daviddrysdale** [comment]
Works for me; what version are you using?

``` pycon
>>> import phonenumbers
>>> print phonenumbers.__version__
6.2.0
>>> phonenumbers.is_valid_number(phonenumbers.parse('0138 6000', 'DE'))
True
```

**Comment by ywang-va** [comment]
sorry, i was using  old version, everything works fine now. thanks
