### ISSUE TITLE
FIXED_LINE_OR_MOBILE issue

### ISSUE THREAD

**Issue by anishmenon** [daviddrysdale/python-phonenumbers#49]
When I try to get  FIXED_LINE_OR_MOBILE . My number +1 414-719-88XX is a mobile number with AT&T. But it says its an fixed line . 

but on freecarrierlookup.com i got the genuine result 

Phone Number:   14147198856
Carrier:    ATT Mobility
Is Wireless:    y ( mobile)
SMS Gateway Address:    4147198856@txt.att.net
MMS Gateway Address:    4147198856@mms.att.net

please help . where we will get the update

**Comment by daviddrysdale** [comment]
I get `FIXED_LINE_OR_MOBILE`:

``` pycon
>>> import phonenumbers
>>> phonenumbers.__version__
'7.0.1'
>>> x = phonenumbers.parse("14147198856", "US")
>>> phonenumbers.number_type(x) == phonenumbers.PhoneNumberType.FIXED_LINE_OR_MOBILE
True
```

This is the same result as the upstream code ([online version](http://libphonenumber.appspot.com/)) code gives, so I can't see a problem with the Python code here.

**Comment by anishmenon** [comment]
@daviddrysdale .

phonenumbers.number_type(x) == phonenumbers.PhoneNumberType.MOBILE
tht returns FALSE.

but its an mobile number .

i know there is no prob with python code . but where we can the updated of resource for phonenumbers package

**Comment by daviddrysdale** [comment]
The library can't tell, just from the number, whether it's a fixed line or a mobile number, and so returns `FIXED_LINE_OR_MOBILE`.  I would guess that freecarrierlookup.com actually does an external query of the relevant live number databases; this library is entirely local and so can only answer "either".

(In other countries, e.g. the UK, the numbering plans for landlines and cellphones are completely different, and so it's possible to distinguish the two just by looking at the number.)

**Comment by anishmenon** [comment]
its ok . 

but +918111903111 its ' Idea cellular india' . but the carrier info from libphonenumber is blank . how we can update the lib .

**Comment by daviddrysdale** [comment]
The metadata comes from the [upstream](https://github.com/googlei18n/libphonenumber) project, so you should report missing data there.

**Comment by Avinash-aka-Theblank** [comment]
Is it possible to get if the number is Landline or Mobile using phonenumber package ?

**Comment by daviddrysdale** [comment]
> Is it possible to get if the number is Landline or Mobile using phonenumber package ?

Sometimes, it depends on the region.  
- Some regions (e.g. US) use the same numbering space for both fixed line and mobile, so only `FIXED_LINE_OR_MOBILE` can be returned.
- Some regions (e.g. UK) use distinct numbering spaces for `FIXED_LINE` and `MOBILE` and so the two can be distinguished.

**Comment by Avinash-aka-Theblank** [comment]
So let's just take U.S for example. How can I find if the number is Landline or Mobile?

**Comment by daviddrysdale** [comment]
> So let's just take U.S for example. How can I find if the number is Landline or Mobile?

You can't, at least not offline (and therefore not with this library).

**Comment by Avinash-aka-Theblank** [comment]
Is there any other way? Like I have a database of numbers and I need to classify them as Mobile or Landline number across countries.
