### ISSUE TITLE
Source not on pypi

### ISSUE THREAD

**Issue by tow** [daviddrysdale/python-phonenumbers#5]
Can you push a tar.gz to pypi for the latest release (3.9b1 as I write this)?

At the moment pypi's only got up to 3.7b1, which means that's the latest version that pip will install when asked to.

**Comment by daviddrysdale** [comment]
That's odd, I see 3.9b1 at http://pypi.python.org/pypi/phonenumbers/. Am I missing something?

**Comment by daviddrysdale** [comment]
Aha, looks like I've been doing `setup.py register` rather than `setup.py upload`.  Should be updated now.
