### ISSUE TITLE
Inconsistent treatment of French premium (4- and 6- digit) numbers

### ISSUE THREAD

**Issue by steveswales** [daviddrysdale/python-phonenumbers#50]
I noticed that French premium numbers (4- and 6- digit numbers starting with 1, 3, or 118) seem to be recognized for formatting, but return False in validity test, e.g.

> > > p=phonenumbers.parse("118712", "FR")
> > > str(phonenumbers.format_number(p, phonenumbers.PhoneNumberFormat.NATIONAL))
> > > '118 712'
> > > phonenumbers.is_valid_number(p)
> > > False

**Comment by daviddrysdale** [comment]
That sounds like a metadata issue (and the [online Java version](http://libphonenumber.appspot.com/) gives similar results), so could you raise this against the [upstream project](https://github.com/googlei18n/libphonenumber) please?

**Comment by steveswales** [comment]
Actually, it seems there is special short number code which validates and parses these numbers. And, they work!

Thanks,

-steve
