### ISSUE TITLE
List MNO of country

### ISSUE THREAD

**Issue by moas** [daviddrysdale/python-phonenumbers#54]
Hello!

How to get a mobile network operator's list of countries ? I want to get the list just using as parameters the alpha2 (fr) code of country or international code (+33).
Sorry for my english, I'm french man :)

Thx

**Comment by daviddrysdale** [comment]
I don't think there's a way to do that with the API (although you could ask at the [upstream project](https://github.com/googlei18n/libphonenumber) to confirm).

If I understand what you're after correctly, some of the information you're after is in the metadata:

```
% egrep -h "^33" resources/carrier/*/* | awk -F\| '{print $2}' | sort -u
Bouygues
Orange France
SFR
% egrep -h "^41" resources/carrier/*/* | awk -F\| '{print $2}' | sort -u
Orange
Sunrise
Swisscom
Tele4u
```

However, it's not a particularly reliable mapping -- not all countries have number ranges by network operator.

```
% egrep -h "^44" resources/carrier/*/* 
%
```

So I'm not sure that even manually grepping the metadata will get what you want, I'm afraid.
