### ISSUE TITLE
theoretical number

### ISSUE THREAD

**Issue by dkavraal** [daviddrysdale/python-phonenumbers#58]
Theoretically this number should belong to Russia I guess. +9782353434

It's a made up number. There is no country as +978 despite for 971, 972, 973, 974... However there is a country +9

What do you think?

PS: The method throws a NumberParseException.INVALID_COUNTRY_CODE

**Comment by daviddrysdale** [comment]
Er, mostly I think that the Python code gives the same answer as the upstream Java code so I don't care :-)

As you say, there are various 97x country codes, but not 978 -- maybe it's reserved for something.  I'm not aware of a +9 country code on its own, though -- that would be odd as various other territories (e.g. Pakistan) would then be inside that numbering space.
