### ISSUE TITLE
Get country code for international prefix

### ISSUE THREAD

**Issue by tspecht** [daviddrysdale/python-phonenumbers#59]
If I would have an valid internal number like +49123456789 is there any way I could get the country code of the numbers country (which would be in this example "de" or "DE" because its +49)?

**Comment by daviddrysdale** [comment]
``` pycon
>>> import phonenumbers
>>> x = phonenumbers.parse('+49123456789', None)
>>> phonenumbers.region_code_for_number(x)
'DE'
```
