### ISSUE TITLE
National numbers outside the US and Canada are always prefixed with 01

### ISSUE THREAD

**Issue by SBoudrias** [daviddrysdale/python-phonenumbers#61]
When formatting a number from outside the US or Canada as a national number, this library always prepend a `01` in front.

Here's an example with a number from Mexico

``` python
num = phonenumbers.parse('+523222222099')
phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.NATIONAL)
// OUT: u'01 322 222 2099'
```

I'd expect the national number to be `322 222 2099`.

**Comment by daviddrysdale** [comment]
I get the same result from the [upstream Java code](https://libphonenumber.appspot.com/phonenumberparser), so please could you raise your worry with them?

(The Python version just tracks the Java code, so if the same behaviour occurs with both it's not a python-phonenumbers specific issue.)
