### ISSUE TITLE
New Brazil mobile numbers are failing is_valid_number() method.

### ISSUE THREAD

**Issue by jordanmnunez** [daviddrysdale/python-phonenumbers#62]
``` bash
>>> n = phonenumbers.parse("+5586998975814")
>>> phonenumbers.is_valid_number(n)
False
```

According to [National Numbering Plan for Brazil](http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200001D0001PDFE.pdf) , mobile numbers have been slowly migrating from  '+55 XX XXXX XXXX' to '+55 XX 9XXXX XXXX'. Eventually these numbers could be 2-9. 

The library recognizes this to be a valid mobile number: http://libphonenumber.appspot.com/

**Comment by daviddrysdale** [comment]
This is valid for me on the current code; what version are you using?

``` pycon
>>> import phonenumbers
>>> n = phonenumbers.parse("+5586998975814")
>>> phonenumbers.is_valid_number(n)
True
>>> phonenumbers.__version__
'7.2.1'
```

**Comment by jordanmnunez** [comment]
live:

``` bash
>>> phonenumbers.__version__
'6.2.0'
```

This was diff from local version which was causing huge confusion.
SMH
@daviddrysdale thanks for checking + sorry for confusion.
