### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by kylefox** [daviddrysdale/python-phonenumbers#64]
First off, great library — thanks very much for providing it :+1: 

I'm wondering if release notes or a changelog is available. I can't seem to find one, apologies if I've simply missed it ...

If there aren't release notes, would you consider adding them somewhere? It would make upgrading much simpler :)

Thanks!

**Comment by daviddrysdale** [comment]
Does the [HISTORY](https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/HISTORY) file cover what you want?  It's usually just a copied description of the code changes from the [upstream project](https://github.com/googlei18n/libphonenumber)'s [release notes](https://github.com/googlei18n/libphonenumber/blob/master/java/release_notes.txt); I don't bother describing metadata changes (and that usually means that only an x.y.0 release has code changes, as x.y.N releases (for N>=1) normally only have metadata changes).

**Comment by kylefox** [comment]
Ah, yep the HISTORY file is exactly what I was looking for — thanks!

Maybe worth linking to from the README?

**Comment by kylefox** [comment]
Adding a link to the upstream release notes might be useful as well.

**Comment by daviddrysdale** [comment]
Good idea, fixed in 0d649ad5b436515b87e4acb2760f307351712663

**Comment by kylefox** [comment]
:+1:
