### ISSUE TITLE
raise NumberParseException on invalid number with unicode

### ISSUE THREAD

**Issue by houqp** [daviddrysdale/python-phonenumbers#65]
HI,

We just got an UnicodeDecodeError for an invalid user input: '\xe2\x80\x8b1-123-456-789'. I suggest we catch that in the library and throw out a NumberParseException.

**Comment by daviddrysdale** [comment]
That input is the byte string for the UTF-8 encoding of `u'\u200b1-123-456-789'` (where `\u200b` is [ZERO WIDTH SPACE](http://www.fileformat.info/info/unicode/char/200B/index.htm)), but the library is currently expecting (on Python 2.x) to receive a valid string -- either a `unicode` string or a plain `str` string with ASCII contents.

I'll think about whether it makes sense to unilaterally assume any `str` input is actually UTF-8, but in the meanwhile you can probably work around the problem by ensuring you feed in `unicode` objects.

**Comment by houqp** [comment]
Good call, I will decode all the input before feeding to the library. thank you :)
