### ISSUE TITLE
7.3.0, 7.3.1 missing from changelog

### ISSUE THREAD

**Issue by adamchainz** [daviddrysdale/python-phonenumbers#76]
https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/HISTORY doesn't list 7.3.0, or 7.3.1, but it lists the others.

**Comment by daviddrysdale** [comment]
I typo'ed the version number when I added the 7.3.0 update, fixed in commit 48fcf7045e64fa84a6b37a7cb74689ac2bfd01ee, thanks for spotting.

(I don't normally update the `HISTORY` file for changes in the patch version, because it's normally just metadata changes.)

**Comment by adamchainz** [comment]
Thanks!
