### ISSUE TITLE
PyPI Not Updated

### ISSUE THREAD

**Issue by HeyBillFinn** [daviddrysdale/python-phonenumbers#83]
I'm not sure the mechanics behind how PyPI gets updated, but it's still serving [version 7.5.2](https://pypi.python.org/pypi/phonenumbers). Is there a required manual step to update it to version 7.6.0?

**Comment by kevin-brown** [comment]
Just verifying this, [7.6.0](https://pypi.python.org/pypi/phonenumbers/7.6.0)/[7.6](https://pypi.python.org/pypi/phonenumbers/7.6) was never uploaded to PyPI.

**Comment by daviddrysdale** [comment]
Odd, I could have sworn I did the upload step.  Anyhow, should be there now -- apologies for the delay.
