### ISSUE TITLE
Move HISTORY.md to the base dir of the repo

### ISSUE THREAD

**Issue by kavdev** [daviddrysdale/python-phonenumbers#85]
Hi,

I'm using a service called [pyup](https://pyup.io/) (which uses [changelogs.net](https://changelogs.net/) to grab changelogs). It's currently unable to find your changelog because it's in the python subdirectory.

Would it be possible to move the changelog to the base dir of the repo?

**Comment by kavdev** [comment]
Nevermind. Looks like you've already gone ahead with it haha

**Comment by kavdev** [comment]
Wait, do you plan on having duplicates in the base dir and the python dir?

**Comment by kavdev** [comment]
Disregard previous comments. My brain mixed up README and HISTORY for a quick second...

**Comment by daviddrysdale** [comment]
Can I check: has pyup ever worked for python-phonenumbers in the past?
(In other words, is it a coincidence that you raised this just after I renamed the HISTORY file?)

By the way, I should point out that I don't normally do HISTORY updates for minor releases (most of the time they just have metadata updates, no code changes).

**Comment by kavdev** [comment]
Yes, it was just a coincidence.

The pyup service creates a pull request when a dependency is updated and displays the most recent changelog item in the PR comment. It would just be convenient to see what's changed at a glance.

For reference: https://changelogs.net/?query=python-phonenumbers
Working package: https://changelogs.net/?query=dj-stripe

If it had worked in the past, there would be an entry on the site. Also, notice how the changelog in dj-stripe is split by version. It's pretty helpful.

**Comment by kavdev** [comment]
Update: It's now being found: https://changelogs.net/phonenumbers/

**Comment by daviddrysdale** [comment]
I wonder why that started working...

**Comment by kavdev** [comment]
Not quite sure. They must be improving their search algorithm.
