### ISSUE TITLE
Request Update to Upstream libphonenumber-7.7.3

### ISSUE THREAD

**Issue by lazyvalue** [daviddrysdale/python-phonenumbers#88]
Hi! When possible, can you please update this lib to match 7.7.3 of the Java version? We're waiting on some region updates. Thanks much!

**Comment by daviddrysdale** [comment]
You're keen -- you raised this 10 hours before the 7.7.3 announcement went out on the mailing list!

By the way, if you want to pull in a local copy of upstream metadata changes yourself, you just need to copy over the contents of the `resources/` directory from libphonenumber and run `make metaclean test` in `tools/python/`.
