### ISSUE TITLE
Not correctly parsing australian numbers without area code prefix

### ISSUE THREAD

**Issue by pg1671** [daviddrysdale/python-phonenumbers#9]
When an australian number has no area code specified the national number returned does not add the missing area code.

Eg. 30004000 would be a brisbane phone number its national number would be 730004000 but:
phonenumbers.parse("30004000", "AU")

returns:
PhoneNumber(country_code=61, national_number=30004000L, extension=None, italian_leading_zero=False, country_code_source=None, preferred_domestic_carrier_code=None)

This leads to incorrect national and international numbers when formatted using format_number.

Is python-phonenumbers expected to provide this functionality or should i be pre processing the number and adding the prefix myself?

Thanks.

**Comment by daviddrysdale** [comment]
You do need to start from a nationally diallable number, not just a locally diallable one, so yes you probably need to add the area prefix (there's a [related discussion](https://groups.google.com/d/topic/libphonenumber-discuss/QuexSjkFgkw/discussion) on the mailing list). 

Note that the `parse` call is returning a `PhoneNumber` object, but it's not a [valid](http://libphonenumber.googlecode.com/svn/trunk/javadoc/com/google/i18n/phonenumbers/PhoneNumberUtil.html#isValidNumber%28PhoneNumber%29) phone number (only a [possible](http://libphonenumber.googlecode.com/svn/trunk/javadoc/com/google/i18n/phonenumbers/PhoneNumberUtil.html#isPossibleNumberWithReason%28PhoneNumber%29) one): 

```
>>> import phonenumbers
>>> x = phonenumbers.parse("30004000", "AU")
>>> phonenumbers.is_valid_number(x)
False
>>> phonenumbers.is_possible_number(x)
True
```

By the way, this is probably more of a question for the upstream [libphonenumber](http://code.google.com/p/libphonenumber/) folk -- the base algorithms and per-country metadata come from there (this repo is just the Python port).  You can always check things out there with the [online number parser](http://libphonenumber.appspot.com/) -- when I put in "30004000" and "AU" into that it indicates that the number is not valid, same as in Python.
