### ISSUE TITLE
International number incorrect parse

### ISSUE THREAD

**Issue by Mogost** [daviddrysdale/python-phonenumbers#91]
```
In: phonenumbers.format_number(phonenumbers.parse('+1 61447442511', 'US'), phonenumbers.PhoneNumberFormat.INTERNATIONAL)
Out: '+1 61447442511'
```

```
In: phonenumbers.format_number(phonenumbers.parse('+1 510-599-2010', 'US'), phonenumbers.PhoneNumberFormat.INTERNATIONAL)
Out: '+1 510-599-2010'
```
Why "out" is in this two cases are in different formats.

**Comment by daviddrysdale** [comment]
The Python code is giving the same result as the upstream code, as shown in the online demo:

http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+61447442511&country=US
http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+510-599-2010&country=US

The results for the first number also give a clue as to why:
```
Result from isPossibleNumber()	false
Result from isPossibleNumberWithReason()	TOO_LONG
```

**Comment by Mogost** [comment]
Sorry. Understand that last 2 numbers are ext. number.
correct version for  '+1 61447442511' is '+1 614474425 ext. 11'
