### ISSUE TITLE
International number is not considered valid

### ISSUE THREAD

**Issue by MoonWatcher582** [daviddrysdale/python-phonenumbers#92]
Despite the demo showing that the phone number +972559416222 is a valid number, version 8.2.0 of the python library's is_valid_number returns false for this number. 

Demo result can be seen here: https://libphonenumber.appspot.com/phonenumberparser?number=%2B972559416222&country=US

**Comment by daviddrysdale** [comment]
Works for me:
```pycon
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>> x = phonenumbers.parse("+972559416222", "US")
>>> phonenumbers.is_valid_number(x)
True
>>> phonenumbers.__version__
'8.2.0'
```

What's your platform/Python version etc.?

**Comment by MoonWatcher582** [comment]
Thank you for the quick reply! Fortunately, it looks like this was a configuration issue on our end.

**Comment by gabn88** [comment]
Could you please elaborate what the issue was? Having the same issue now.
