### ISSUE TITLE
Incorrect parsing of phone number

### ISSUE THREAD

**Issue by prafulbagai** [daviddrysdale/python-phonenumbers#94]
Why are strings starting/ending with alphabets/special characters tagged as valid phone number?
```

import phonenumbers

x = '+442083661177--'
x = phonenumbers.parse(x, None)
print x
print phonenumbers.is_possible_number(x)  # True
print phonenumbers.is_valid_number(x)  # True

```

**Comment by daviddrysdale** [comment]
The short answer is 'because that's what the [upstream code](https://github.com/googlei18n/libphonenumber) also [does](http://libphonenumber.appspot.com/phonenumberparser?number=%2B442083661177--)'.   Ask upstream for a definitive answer, but I think it allows for e.g. extensions.
