### ISSUE TITLE
Invalid German Number +491765770313

### ISSUE THREAD

**Issue by AbdurRehman91** [daviddrysdale/python-phonenumbers#95]
hi.i am facing a issue as in my case my test case number is +491765770313 is being consider invalid by the library.i am using django-phoneNumber-field which is basically a wrapper around this library.i have tested other samples German phone numbers which are greater in length than this,and they are working fine.E.g +49492180185611 series.

**Comment by daviddrysdale** [comment]
Works for me; please check your library version.
```pycon
>>> import phonenumbers
>>> print phonenumbers.__version__
8.4.0
>>> x = phonenumbers.parse('+491765770313')
>>> phonenumbers.is_valid_number(x)
True
```

**Comment by AbdurRehman91** [comment]
hi.thanks for the help.issue was in the version.upgrading to 8.4.0 has solved the issue
thanks alot for the help
