### ISSUE TITLE
Argentina phone numbers are formatted incorrectly

### ISSUE THREAD

**Issue by tsx** [daviddrysdale/python-phonenumbers#96]
A range of perfectly reachable numbers in Argentina (+54) are formatted incorrectly.

Here's an example number: +5450490000 (An actual phone number I have is a few last digits different from that example to avoid disclosing personal information). The issue appears across a large range of numbers +5499999999 - +5400000000.

```python
>>> parsed = phonenumbers.parse('+5450490000')
>>> phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
'+54 NA'
```

The number appears to be [invalid](http://libphonenumber.appspot.com/phonenumberparser?number=%2B5499999999) in [upstream library](https://github.com/googlei18n/libphonenumber/issues/1697), but until they fix it, `phonenumbers` should throw exception instead of silently producing incorrect result.

A quick investigation on my end shows that the last well-behaving version was 7.7.3.

**Comment by daviddrysdale** [comment]
Outputting `NA` is definitely a bug -- thanks for spotting and for narrowing it down to around 7.7.3
